LazyVim/LazyVim

lua/lazyvim/plugins/ui.lua
=> fix(bufferline): load bufferline on VeryLazy event (#35)

lua/lazyvim/plugins/ui.lua
=> Update ui.lua (lualine extension "nvim-tree" -> "neo-tree")

lua/lazyvim/config/autocmds.lua, lua/lazyvim/config/init.lua
I draft proposed solution for the problems described in #150
=> fix(config): add groups to autocommands

lua/lazyvim/plugins/treesitter.lua
=> fix: Check for nil value in treesitter-textobjects init

lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/ui.lua
same as https://github.com/folke/lazy.nvim/pull/529
these obsoleted icons will be rendered as CJK characters for CJK font users, replace them with correct new icons
=> fix(icons): replace obsolete Nerd icons

lua/lazyvim/plugins/treesitter.lua
Needs https://github.com/nvim-treesitter/nvim-treesitter/pull/4433 but I think it'll benefit anyone using Lua (similar to regex highlights in js)
=> feat: add luap to nvim-treesitter ensure_installed

lua/lazyvim/plugins/treesitter.lua
Requires commit from this PR https://github.com/nvim-treesitter/nvim-treesitter/pull/4529, but I hope people find it helpful :slightly_smiling_face:
=> feat(treesitter): add luadoc

lua/lazyvim/config/autocmds.lua
I just added a autocmd to fix `no such file or directory` when saving a file, hope it will be useful.
=> feat(autocmds): add auto create dir

lua/lazyvim/plugins/editor.lua
Adds document/workspace diagnostics and todo/fixme telescope keymaps.
=> feat(keymaps): add some telescope keymaps

lua/lazyvim/plugins/extras/dap/core.lua, lua/lazyvim/plugins/ui.lua
I am not sure what the criteria for adding default keybindings to LazyVim, just want to share a few missing keys from my config.
Plus a lualine components showing debug adapter status.
=> feat(dap): add more keybindings and lualine component

lua/lazyvim/plugins/extras/dap/core.lua
=> Change DAP REPL binding from open to toggle

lua/lazyvim/health.lua
This PR removes deprecated API warnings on health check.
=> fix(health): remove deprecated api warning

lua/lazyvim/plugins/extras/coding/copilot.lua
Upstream changes happened here: https://github.com/zbirenbaum/copilot-cmp/pull/67
=> Latest copilot-cmp requires passing opts to _on_insert_enter

lua/lazyvim/config/keymaps.lua
=> fix: remove debug notify

lua/lazyvim/plugins/extras/lang/go.lua
Just realised that we set the settings in the wrong place, apologies..
=> fix(go): actually set semantic tokens

lua/lazyvim/plugins/extras/lang/ruby.lua
Following the example of go I wanted to go ahead and try to add the setup for ruby.
This is the configuration I currently use locally so it does work pretty well.
=> Add ruby as extras for languages

lua/lazyvim/config/options.lua
=> fix(options): update comment

lua/lazyvim/plugins/extras/editor/mini-files.lua
Very useful features, copy straight from the doc of mini.files
=> feat(mini.files): "g." to toggle hidden files

lua/lazyvim/plugins/extras/lang/elixir.lua
Hi folke, adding support for Elixir in extras.
Not sure if you'd want this but here it is :)
Thanks for all the work in the neovim community.
=> Add Elixir support and config

lua/lazyvim/plugins/extras/lang/go.lua
The null-ls sources *could* be controversial, but they provide niceties most people would appreciate I'd think
=> feat(go): add fine-tuned LSP options, add some null-ls sources

lua/lazyvim/plugins/extras/lang/clangd.lua
Not sure if the file should be called c or clangd (lsp name, supports c/c++/objc/objc++)
=> feat(lang): add C/C++ support

lua/lazyvim/plugins/colorscheme.lua
=> feat(catppuccin): match navic bg with lualine

lua/lazyvim/plugins/treesitter.lua, lua/lazyvim/plugins/ui.lua, lua/lazyvim/plugins/util.lua
Just another smidge more documentation to describe the component plugins of LazyVim.
=> Add more documentation

lua/lazyvim/plugins/editor.lua
use `<leader>"` to search register through telescope
=> feat: add a keybind to search register

lua/lazyvim/plugins/extras/lang/java.lua
as title says: this PR adds `java-test` and `java-debug-adapter` support to the language package; as there is no official `neotest` plugin yet, it uses the features from `nvim-jdtls` for running tests
=> feat: add test and debug support for Java extension

lua/lazyvim/plugins/extras/lang/yaml.lua
add `yaml` language extension incl. yaml schema companion
=> feat: add yaml language extension

lua/lazyvim/plugins/treesitter.lua
better highlighting for jsdoc comment
=> feat(treesitter): add jsdoc to ensure_installed

lua/lazyvim/plugins/extras/lang/python.lua
The hover ability of ruff seems not be correctly disabled.
=> fix: disable ruff hover correctly

lua/lazyvim/config/autocmds.lua
Resolves https://github.com/LazyVim/LazyVim/issues/1241
=> Restore tabpage on resize

lua/lazyvim/plugins/coding.lua
Add function and keymap to toggle mini pairs.
=> feat(mini-pairs): add toggle function

lua/lazyvim/config/init.lua, lua/lazyvim/plugins/extras/formatting/prettier.lua, lua/lazyvim/plugins/extras/lang/cmake.lua, lua/lazyvim/plugins/extras/lang/docker.lua, lua/lazyvim/plugins/extras/lang/go.lua, lua/lazyvim/plugins/extras/lang/omnisharp.lua, lua/lazyvim/plugins/extras/lang/terraform.lua, lua/lazyvim/plugins/extras/lang/typescript.lua, lua/lazyvim/plugins/lsp/init.lua
=> feat: use none-ls instead of null-ls

lua/lazyvim/plugins/extras/lang/go.lua
=> fix(extras.go): remove unneeded formatters since gopls handles them

lua/lazyvim/plugins/extras/util/project.lua
Follows same logic from alpha and mini-starter.
=> feat(dashboard): add projects if enabled

lua/lazyvim/plugins/editor.lua
Fix missing changes from https://github.com/LazyVim/LazyVim/commit/d28c69e49eab62b45f7d1562b3bc00afee5fbb65
=> fix(which-key): change surround group key

lua/lazyvim/config/init.lua, lua/lazyvim/plugins/extras/coding/codeium.lua
re-activate `codeium`extension (free alternative to GH Copilot), which is maintained by Exafunction now
=> [feat] add codeium extension

lua/lazyvim/plugins/ui.lua
hi, small modification :) to v.10
thanks
=> adding mini.starter to lualine disabled files

lua/lazyvim/plugins/extras/ui/alpha.lua, lua/lazyvim/plugins/extras/ui/mini-starter.lua, lua/lazyvim/plugins/extras/util/project.lua, lua/lazyvim/plugins/ui.lua, lua/lazyvim/util/plugin.lua
https://github.com/glepnir/dashboard-nvim redirects to https://github.com/nvimdev/dashboard-nvim
=> fix(dashboard-nvim) repository has moved to nvimdev/dashboard-nvim

lua/lazyvim/plugins/ui.lua
BufferLine has capital letter `L`
=> fix(ui): fix BufferLineClose commands

lua/lazyvim/plugins/ui.lua
@folke my pr was merged to https://github.com/nvimdev/dashboard-nvim/pull/396 so here's this one as promised. Though since it's user configurable not sure it's necessary?
=> style(dashboard): remove unnecessary brackets from keys

lua/lazyvim/plugins/extras/lang/python-semshi.lua
I don't use python too heavily (definitely not daily) but these are improvements I use locally because I find them to be worse than tree-sitter's semantically
Ping @lkhphuc since you added the extra
=> fix(extras.python-semshi): improve highlights

lua/lazyvim/util/telescope.lua
the map function receives a opts table but the desc is overridden by telescope. until that changes, this seems like a good alternative
=> fix(telescope): anonymous keymap

lua/lazyvim/plugins/extras/lang/haskell.lua
As requested by @gacallea in https://github.com/mrcjkb/haskell-tools.nvim/issues/290.
@gacallea could you please test this? :smile:
=> feat(lang): add Haskell config

lua/lazyvim/plugins/extras/lang/helm.lua
Closes #2251 
See related discussion #1389
=> feat(lang): add support for helm chart templates

lua/lazyvim/plugins/extras/lang/terraform.lua
Closes #2234
Add telescope integrations for:
- https://github.com/ANGkeith/telescope-terraform-doc.nvim
- https://github.com/cappyzawa/telescope-terraform.nvim
=> feat(lang): add telescope terraform integrations

lua/lazyvim/plugins/ui.lua
just like `<leader>ff` keymap for telescope
=> feat(ui): dashboard files searches git files if in git repo

lua/lazyvim/util/extras.lua
=> fix(extras): accept symlinks in User `extras` directory

lua/lazyvim/util/telescope.lua
=> fix(util.telescope): make `show_untracked` configurable

lua/lazyvim/plugins/extras/editor/dial.lua
I just spent few hours trying to figure out how to set up dial.nvim, so I made this PR in the hope of saving other people's time)
I expect that people will modify the options and will create their own groups for dial. So I added few comments on how it works
=> feat(extras): add dial extra

lua/lazyvim/plugins/extras/lang/python-semshi.lua
I decided to just PR this in from my config for others that are using it, but I've switched to basedpyright for semantic highlighting now though :)
=> fix(python-semshi): better highlights

lua/lazyvim/plugins/extras/editor/harpoon2.lua
Basically uses loop for individual harpoon file key spec
=> fix: optimizes harpoon keys

lua/lazyvim/plugins/extras/util/dot.lua
I work with shell files a lot , so this basically adds support for shell files
=> feat(dot): add bashls and shellcheck

lua/lazyvim/util/toggle.lua
=> fix(toggle): use new `inlay_hint.enable()` signature

lua/lazyvim/plugins/extras/editor/trouble-v3.lua
=> fix(trouble_v3): show error only when `trouble_v3` is enabled

lua/lazyvim/util/lualine.lua
=> feat(lualine): make path trimming configurable by user

lua/lazyvim/plugins/extras/editor/refactoring.lua
More on:
https://github.com/ThePrimeagen/refactoring.nvim#features
=> feat(editor): add refactoring.nvim

lua/lazyvim/plugins/lsp/init.lua
=> fix(lsp): check if `diagnostics.signs` is disabled by user

lua/lazyvim/plugins/extras/lang/typescript.lua
since LazyVim have toggle inlayhint keymap, it make sense to configure them for each extra languages provided. In this commit I just add the configuration for typescript, since IDK how to configure the rest of lang extras that was provided.
=> feat(typescript): configure inlayHint

lua/lazyvim/plugins/extras/lang/omnisharp.lua
Based on https://alpha2phi.medium.com/neovim-pde-net-c-417fe33ffbaf
=> feat: support neotest dotnet

lua/lazyvim/plugins/extras/editor/refactoring.lua
shows a message with information about the refactor on success  i.e. [Refactor] Inlined 3 variable occurrences
=> fix(refactoring): show refactored success msg

lua/lazyvim/plugins/editor.lua
- Add `<leader>sj` telescope jumplist keymap
=> feat(telescope): add telescope jumplist keymap

lua/lazyvim/plugins/extras/lang/typescript.lua
Adds a keymap to select typescript version
=> fix: vtls add select ts version

lua/lazyvim/config/options.lua, lua/lazyvim/plugins/ui.lua
=> fix(ui): do not add trouble to lualine when aerial is enabled

lua/lazyvim/plugins/extras/lang/r.lua
=> R.nvim make R output themed by neovim theme

lua/lazyvim/plugins/extras/util/mini-hipatterns.lua
added support for heex, rust and svelte to hipatterns files in the config for min.hipatterns
=> Update mini-hipatterns.lua config to add support for heex, rust and svelte files

lua/lazyvim/config/keymaps.lua
`<leader><tab>x` to close all tab pages except the current one
=> feat(keymaps): add keymap to close all tab pages except the current one

lua/lazyvim/plugins/extras/lang/svelte.lua
I'm not sure if prettier should be set up for the svelte filetype here in the svelte extra or in the formatting.prettier extra.
=> fix(svelte): added organize imports and prettier

lua/lazyvim/plugins/extras/lang/nushell.lua
This will add minimal support for [Nushell](https://www.nushell.sh/) include lspconfig and treesitter highlight
Close #2164
=> feat(nushell): add minimal support

lua/lazyvim/plugins/extras/lang/nix.lua
In the future we can add:
- dap / debugger support, if this is ever possible or needed.
- extend neotest, if this is ever needed, for most people I suspect not needed.
- linting, if this is ever needed.
- ~~maybe enhance nvim-cmp behavior with nixpkgs, rust lang extension crates.nvim does smt with nvim-cmp, other language extensions don't.~~
I think its already good to merge this PR, we can add these enhancements later, if they are ever needed.
=> feat(lang): add nix language support

lua/lazyvim/util/extras.lua
Remove extra space between icon and text (for source label).
=> fix(ui): remove extra space

lua/lazyvim/plugins/treesitter.lua
```c
printf("%s\n", "Finally!");
```
=> feat(treesitter): add printf

lua/lazyvim/plugins/extras/lang/gleam.lua
Added [Gleam lang](https://gleam.run/) support.
=> feat(extras): added gleam lang support

lua/lazyvim/plugins/extras/lang/php.lua
Configures tree-sitter, phpactor as LSP server and xdebug/vscode-php-debug as DAP server.
=> feat(lang): added php support

README.md
As requested, here's a link to my book from the README. I'll add the video and this link to the main page of lazyvim.org as well.
=> feat(docs): add link to LazyVim For Ambitious Developers to README

lua/lazyvim/plugins/extras/editor/aerial.lua, lua/lazyvim/plugins/extras/editor/navic.lua
=> fix(lualine): only show one Lualine component for symbols

doc/LazyVim.txt, lua/lazyvim/plugins/extras/lang/clojure.lua
This adds support to Clojure as an extra _lang_ configuration. 
Closes https://github.com/LazyVim/LazyVim/pull/1484
@folke I read the docs and couldn't find a recommendation on _how_ to suggest features, so I figured opening a PR should be enought. please let me know if I should do anything else.
=> feat(lang): add clojure support

lua/lazyvim/plugins/extras/lang/helm.lua
according to this comment  https://github.com/LazyVim/LazyVim/commit/ab41ff551b89fde27a0225bc1aa7245bcaec472e#r142924660
=> fix(helm): missing dependency

lua/lazyvim/plugins/extras/lang/rust.lua
fixes https://github.com/LazyVim/LazyVim/issues/3543
=> fix(lang): neotest not loading rust tests

lua/lazyvim/plugins/extras/coding/copilot-chat.lua
- Just a small fix for which-key in visual mode that the authors forgot to add.
- As copilot-chat has just been added to extras so i think this is new.
=> fix(extras.copilot-chat): small ui fix for which-key in visual mode

lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/extras/editor/fzf.lua, lua/lazyvim/plugins/ui.lua, lua/lazyvim/util/init.lua, lua/lazyvim/util/pick.lua, lua/lazyvim/util/root.lua, lua/lazyvim/util/telescope.lua
New extra with an initial implementation of fzf-lua.
=> feat(extras): added fzf-lua

lua/lazyvim/plugins/extras/lang/php.lua
Fixed the issue of php formatting not working in extras.lang.php
=> fix(extra-lang-php): formatting and linting

lua/lazyvim/plugins/extras/util/project.lua
- `ctrl-s` search_in_project_files
- `ctrl-w` change_working_directory
- `ctrl-d` delete_project
- `ctrl-r` recent_project_files
=> feat: add some fzf-lua keymap

lua/lazyvim/plugins/extras/editor/outline.lua
Allows to toggle window in outline using Ctrl-k /ctrl+j
=> feat(outline): free ctrl-k /ctrl+j

lua/lazyvim/util/lazygit.lua
- The current implementation doesn't support multi-module/monorepo project where `<repo>/.git` can be `gitdir` alias to the main `.git` folder. This PR uses the Git CLI to resolve remote URLs to better support flexible project structure. 
- This PR also adds the support to Bitbucket and GitLab
What's the problem of reading `.git/config`?
- Not all information available there. For instance, some large projects will split a monorepo into smaller submodules, where `.git` is a file that contains the `gitdir` alias.
- There's no promise that `.git/config` has to be existed. Git supports multiple ways to store the git info outside of the default git directory like using `GIT_DIR` env variable.
- Have to do lot of reading and parsing logic.
Why `git remote -v`?
- Only contains remote info with …
=> fix(lazygit): support monorepo structure and other git providers

lua/lazyvim/plugins/extras/util/project.lua
=> feat(project): add fzf-lua keymap descriptions

lua/lazyvim/plugins/extras/lang/python.lua
fix(dap): get the correct debugpy pkg path on windows.
=> fix(dap): get the correct debugpy pkg path on windows

lua/lazyvim/plugins/extras/lang/prisma.lua
=> feat(extra): add prisma support and config

lua/lazyvim/plugins/extras/editor/refactoring.lua
Provide a `pick` function to `refactoring.nvim` similar to `project.nvim`
Fixes #3762
=> fix(refactoring): use `pick` for both Telescope and fzf-lua

lua/lazyvim/util/lazygit.lua
Use `lazy.util.open` on Neovim <=0.10
Closes #3776
=> fix(lazygit): use `lazy.util.open` on Neovim <= 0.10

lua/lazyvim/plugins/extras/util/project.lua
In #3690 there was a [concern expressed](https://github.com/LazyVim/LazyVim/pull/3690#issuecomment-2174024517) about changing `fzf-lua`'s core actions. This PR tries to achieve the same result by manually setting the headers in `fzf_opts["--header"]` and constructing it without use of `fzf-lua.actions`.
Feel free to disregard if you think there's no change necessary in the current code, as this is simply a refactor attempt and does not provide any new functionality.
No
=> refactor(project): use header descriptions without using `fzf-lua.actions`

lua/lazyvim/plugins/extras/util/chezmoi.lua
It is just a small extra for those that use Chezmoi)
=> feat(extras): add chezmoi extra

lua/lazyvim/plugins/extras/lang/erlang.lua
I usually work with Elixir codebases, but sometimes I want to browse and code with Erlang codebases, so here is the config I've been using for Erlang.
=> feat(erlang): add Erlang language

lua/lazyvim/plugins/extras/ui/treesitter-context.lua
Add a which-key toggle for treesitter-context
=> feat(treesitter-context): which-key toggle

lua/lazyvim/plugins/extras/vscode.lua
make use of vscode builtin terminal
**I don't know how to properly handle cwd so it's implemented as a simple toggle**
#4280
=> feat(vscode): make use of vscode builtin terminal

lua/lazyvim/plugins/extras/lang/tex.lua
=> fix(typo): vimtext -> vimtex

lua/lazyvim/plugins/xtras.lua
Offer to users capability to customize priorities of the Extras.
Closes #4584
=> feat(extras): expose `prios` to users for customization

lua/lazyvim/plugins/extras/dap/core.lua
Makes run with args work for jdtls
- Closes #4686
- Closes #4673
=> fix(java): jdtls run with args

lua/lazyvim/plugins/extras/lang/zig.lua
A fresh and minimalist take on #1750.
It only adds what is maintainable (has activity in the past year at least).
Closes #1750.
=> feat(extras): lang/zig

lua/lazyvim/plugins/extras/editor/dial.lua
=> feat(dial): support vue filetype

lua/lazyvim/plugins/extras/ai/copilot-chat.lua
CopilotChat.nvim has moved to main ([ref](https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/665))
https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/665
=> fix(copilot): CopilotChat.nvim has moved to main

lua/lazyvim/config/keymaps.lua
Silences keymap introduced in related PR
https://github.com/LazyVim/LazyVim/pull/4870
=> feat(snacks): silence copy url keymap

lua/lazyvim/plugins/extras/lang/java.lua
This one *actually* fixes the issue, sorry about my previous PR.
=> fix(java): only setup debug adapter config if mason is installed (for real this time)

README-CN.md, README-DE.md, README-JP.md, README-KO.md, README-PT.md, README.md
With the picker and completion changes, fzf and curl need to be installed as part of the try it with docker instructions.
=> chore(README): add new docker dependencies 

README-ES.md
This pull request translates the README.md file from English to Spanish to provide Spanish-speaking users with an easier way to understand the setup and features of LazyVim. The translation includes all sections of the original file, ensuring that the core documentation remains intact while making it more accessible to a broader audience.
None.
None.
=> docs(README): translate README.md to Spanish

lua/lazyvim/plugins/colorscheme.lua
=> feat(colorscheme): add fzf integration to catppuccin

lua/lazyvim/plugins/extras/ai/supermaven.lua
As title, somehow these events have been forgotten, ive checked the git history of it aswell.
=> perf(supermaven): add lazy-loading

lua/lazyvim/plugins/extras/editor/dial.lua
Added support for markdown checkboxes. ( **[ ]** <-> **[x]** )
=> feat(dial): add checkbox augend for markdown

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
As it reads on the title ;)
None.
=> feat(snacks.picker): added <leader>su to search undotree

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
As it reads on the tin can.
N/A
=> feat(snacks.picker): added <leader>si to search icons

lua/lazyvim/plugins/extras/coding/mini-snippets.lua
mini.snippets is out of beta, so I adjusted the description for the extra accordingly
=> feat(snippets): mini.snippets is out of beta

lua/lazyvim/plugins/extras/coding/neogen.lua
Configure neogen and mini.snippets integration.
See also #5593.
=> feat(extras): setup neogen and mini.snippets integration

lua/lazyvim/plugins/extras/coding/yanky.lua
I've introduce snacks picker support for [Yanky history ring](https://github.com/gbprod/yanky.nvim/pull/215), I propose to use it in LazyVim.
=> feat(yanky): use snacks picker for improved yank history navigation

lua/lazyvim/plugins/extras/lang/clojure.lua
https://github.com/PaterJason/cmp-conjure/blob/8c9a88efedc0e5bf3165baa6af8a407afe29daf6/README.md?plain=1#L10
=> fix(lang.clojure): correct cmp-conjure source name
