lua/lazyvim/plugins/ui.lua
Hi!
This is a PR to give you options for a default start screen. Nothing against 'goolord/alpha.nvim', will totally understand rejecting this. 
Functionally it is almost the same:
- Press highlighted letter and it will execute corresponding command.
- User can also navigate to item with `<C-n>/<C-p>` or `<Down>/<Up>`.
Visually there are more differences:
- Items are automatically organized in sections.
- No easy way of adding different icons for different items. Instead there is a single bullet for all items serving as grouping symbol for sections.
- Padding for bullets, section names, and footer are picked manually to achieve some kind of alignment based on the header.
Here is a preview:
=> Use 'mini.starter' as start screen

lua/lazyvim/plugins/ui.lua
Adds mason filetype to disabled list for indentscope
=> Turn off indentscope in Mason

lua/lazyvim/config/keymaps.lua, lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/ui.lua
in a previous version we had buffer switching entries in wk-menu similar to the ones for tabs... 
...they got lost with one of the recent commits, but I think they might sense to have anyway (as the Shift navigation keys are not discoverable via wk menu)...
Also lower-cased the UI wk-menu entry to follow the style of all the others.
=> add missing wk entries for buffer switching; lowercase UI in menu

lua/lazyvim/plugins/extras/lang/typescript.lua
After cleaning up my default treesitter modules (and move most into language specific plugins), I noticed that the typescript module is missing on the tsx parser (for typescript based jsx files)...
=> fix: add tsx treesitter to typescript lang module

lua/lazyvim/config/options.lua
Closes #119.
Note: I've set the viable `opt.shortmess` options outside of the `has("nvim-0.9.0")` feature gate as well, assuming they weren't left out intentionally.
=> fix(config): don't set options to their defaults

lua/lazyvim/plugins/extras/lang/typescript.lua
The current key maps are not wrapped in <cmd><cr> which means the commands will not be triggered.
=> Fix typescript extras Keymaps

lua/lazyvim/config/init.lua
While setting up [copilot-cmp](https://github.com/zbirenbaum/copilot-cmp) I figured adding to the icons in LavyVim is the quickest way for me to get the icon support.
Let me know if there's a simple way to extend the kinds icons if you don't think this is the right place to add it.
=> feat: add copilot icon

lua/lazyvim/config/keymaps.lua, lua/lazyvim/plugins/editor.lua
If `trouble.nvim` is available: use the quicklist / loclist feature of it, otherwise fallback to the buildin ones.
=> feat: use trouble quicklist / loclist if available

lua/lazyvim/plugins/editor.lua
I saw @Cretezy 's pull request and realized I made the same modifications in my own config, but with `move_selection_next` and `move_selection_previous` instead of `cycle_history`. So, this PR
- In `insert` mode
- Adds `<C-j>`/`<C-k>` to scroll in results list
- Adds `<C-n>`/`<C-p>`  to scroll in preview
- In `normal` mode
- Adds `q` to quit
=> Improved Telescope mappings in normal and insert mode

lua/lazyvim/plugins/ui.lua
Currently there is an issue for any file with more than 100 lines where the progress and location indicators are merged into a single word:
This change will fix this and insert at least one space in-between the two.
=> fix(lualine): add a space separator between progress & location

lua/lazyvim/plugins/editor.lua
I've recently switched to LazyVim and really liked many of the out-of-the-box defaults. One keybind I would like though is a way to quickly call `Telescope resume`. I thought `<leader>fR` might be a good place for it. Let me know what you think.
Thanks!
=> feat(telescope): add `<leader>fR` for `:Telescope resume`

lua/lazyvim/plugins/util.lua
Enables persistence of pinned buffers across sessions.
Adds `globals` to session opts
=> feat: persist pinned tabs

lua/lazyvim/plugins/editor.lua
I found myself often wanting to search trough the workspace symbols and i think this keymap makes the most sense, since there is already the same thing for document symbols with `<leader>ss`.
=> feat(telescope): add `<leader>sS` for `:Telescope lsp_workspace_symbols`

lua/lazyvim/config/keymaps.lua
Noticed that this didn't have a description. Thought I could something simple 🙂 
Also, I think there might be a bug (or intentional?) with the web rendered keymaps. There is an early return that causes any keymap without a description to not be built into https://lazyvim.org/keymaps. That means this keymap (`gw`) - although custom - was not in the listed keymaps.
See: inside the `map` function that overrides `vim.keymap.set`
Early return: [build.lua#18-20](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/build.lua#L18-L20)
```lua
if not (opts and opts.desc) then
return
end
```
Later down: [build.lua#25](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/build.lua#L25)
```lua
local desc = opts and opts.desc or ""
```
Nothing urgent, enjoy your holiday!
=> fix: add description for "gw" keymap

lua/lazyvim/plugins/lsp/keymaps.lua
When using null-ls formatter my custom "gd" mapping gets overwritten even thouh null-ls formatters don't have a `definitionProvider".
=> Only map lsp go definition when client has definitionProvider

lua/lazyvim/plugins/treesitter.lua
Fixes a typo, but I think decrement is more appropriate
=> fix: rename more appropriately (also a typo)

lua/lazyvim/plugins/extras/ui/mini-starter.lua
This mirrors the menu item added in alpha-nvim. I named this "Session restore" rather than "Restore session", since mini.starter uses the first letter of the item as the shortcut key.  This way it doesn't conflict with "Recent files".
=> mini-starter: add Session restore to starter menu

lua/lazyvim/plugins/ui.lua
I _think_ `AlphaFooter` should be used instead of `Type` for the footer highlight, especially since [`tokyonight` specifically defines `AlphaFooter` alongside the other alpha highlights](https://github.com/folke/tokyonight.nvim/blob/467d889ba82a74e26821c812aa8e70d7dff04c6c/lua/tokyonight/theme.lua#LL398C8-L398C8).
=> fix(alpha): use `AlphaFooter` highlight for footer section

lua/lazyvim/config/autocmds.lua
Query files aren't just the special window to edit/inspect tree-sitter queries, but also any file in queries/**.scm is considered one. I noticed this bug persisting for a while probably via an autocmd where switching buffers then going back would have the file removed from my bufferline at the top. 
You can reproduce this by cloning any tree-sitter parser and fiddling around with a queries file, then swapping buffers or going back to a query buffer, it sort-of becomes in this weird stuck state (well when using the keybinds I'm familiar with navigation at least), and I have to close and reopen the buffer to fix it.
Thanks!
=> fix(autocmd): remove query from q-to-quit autocmd

lua/lazyvim/plugins/treesitter.lua
Thanks to https://github.com/nvim-treesitter/nvim-treesitter/pull/4524 being merged, Python indents are quite good now
=> feat(treesitter): use Python indents as they've improved greatly

lua/lazyvim/plugins/treesitter.lua
Following nvim-ts and soon neovim
=> refactor(treesitter)!: rename help to vimdoc

lua/lazyvim/plugins/editor.lua
`lsp_workspace_symbols` may fail or return nothing when query is empty. Use the new `lsp_dynamic_workspace_symbols` to dynamically query symbols in the workspace.
Related: https://github.com/nvim-telescope/telescope.nvim/issues/964
Fixes: https://github.com/LazyVim/LazyVim/issues/576
=> fix(telescope): use dynamic workspace symbols

lua/lazyvim/config/autocmds.lua
Add `checkhealth` filetype to `close_with_q` autocmd list.
=> feat(autocmds): add checkhealth filetype to close_with_q list

lua/lazyvim/plugins/lsp/keymaps.lua
Gets the rename command from the inc_rename module (when installed), rather than assuming the default `IncRename`, allowing the user to modify the inc_rename options without having to create a new keymap.
=> feat(keymaps): Get rename command from inc_rename configuration

lua/lazyvim/plugins/treesitter.lua
There is quite a noticable amount of lag for the visual mode `<lt>` mapping because of the `<lt>nop>` mapping made by treesitter. (`<lt>` is escaped `<`)
Before:
After:
[Relevant mapping code is here](https://github.com/nvim-treesitter/nvim-treesitter/blob/b0338a056525e83d88aaa76e8cf396af07410bed/lua/nvim-treesitter/incremental_selection.lua)
=> fix: remove unintentional `<lt>nop>` mapping

lua/lazyvim/plugins/ui.lua
Use `mini.bufremove` to close buffers without breaking window layout in commands such as `BufferLineCloseLeft`, `BufferLineCloseRight`.
=> feat(bufferline): use `mini.bufremove` to close a buffer

lua/lazyvim/plugins/ui.lua
Similar to https://github.com/LazyVim/LazyVim/pull/16
Excludes mason in indent-blankline.nvim
=> exclude filetype mason in indent-blankline.nvim

lua/lazyvim/config/autocmds.lua, lua/lazyvim/config/keymaps.lua
Very minor, but it seems that `autocmds.lua` and `keymaps.lua` are both loaded by the `config/init.lua` module, maybe the comments are out of date?
=> Fix comments on autocmds and keymaps loading

lua/lazyvim/plugins/extras/dap/core.lua
The `mason-nvim-dap` setting name is `automatic_installation`, rather than `automatic_setup`.
https://github.com/jay-babu/mason-nvim-dap.nvim#default-configuration
=> Fix the mason-nvim-dap setting name

lua/lazyvim/plugins/extras/lang/go.lua
Just adding this as it is what I use daily.
I stripped some of my configuration; `null-ls` sources like `gofumpt` and `golangci-lint` as they are subjective, similar to `prettier`.
Also a build tag argument that is passed both to `gopls` and to `neotest-go`, I am unsure how to make it nice to add such a thing.
I personally use the `-tags=integration` argument to ensure `neotest` will run all tests and so that `gopls` wont complain about missing packages, in integration test files.
It is easy to add it to `gopls`:
```lua
{
"neovim/nvim-lspconfig",
opts = {
servers = {
gopls = {
cmd_env = {
GOFLAGS = "-tags=integration",
},
},
},
},
}
```
But it is harder to add to `neotest-go`, as you cannot just merge - so I assume this will result in a list of test adapters with two `neotest-go` …
=> feat(go): add go lang extras

lua/lazyvim/plugins/extras/lang/go.lua
Add a work around based on this comment: https://github.com/golang/go/issues/54531#issuecomment-1464982242
Related to #811
=> fix(go): add workaround to get semantic token highlighting

lua/lazyvim/util/init.lua
This was added in 89db015 and is no longer necessary since b75ed59
=> chore: remove unused upvalue function

lua/lazyvim/plugins/extras/linting/eslint.lua, lua/lazyvim/plugins/lsp/format.lua
The eslint extra will autoformat if there are any diagnostics associated with eslint, but it does not currently respect the stateful autoformat setting (toggled via `<leader>uf`).
=> fix(format): eslint should respect autoformat

lua/lazyvim/config/keymaps.lua
Super minor. Just removing `:` in the Lazy keymap since it has `<cmd>`:
```
map("n", "<leader>l", "<cmd>:Lazy<cr>", { desc = "Lazy" })
```
I'm assuming removing `:` is preferable.
=> fix(keymaps): remove redundant ':' on lazy keymap

lua/lazyvim/plugins/extras/lang/rust.lua
- Fixes indentation
- Moves lspconfig opts to correct location in rust-tools config
- Adds optional neotest-rust
- Allows user to extend rust-tools with `opts` field, without calling rust-tools's `setup()` more than once
=> Add rust improvements

lua/lazyvim/plugins/editor.lua
step to reproduce:
- disable leap.nvim,
- add custom config for flash (not using one from the extras)
- open file type "f", error shown "module leap is missing"
```lua
return {
{
"ggandor/leap.nvim",
enabled = false,
},
{
"folke/flash.nvim",
event = "VeryLazy",
---@type function
keys = function()
return {
{
"<a-m>",
mode = { "n", "x", "o" },
function()
require("flash").jump()
end,
},
{
"<a-s>",
mode = { "n", "x", "v" },
function()
require("flash").treesitter()
end,
},
}
end,
opts = {}
},
}
```
=> fix leap nvim required by flit

lua/lazyvim/plugins/colorscheme.lua
Since LazyVim pre-bundles mason.nvim, it is safe (and makes sense) for the mason integration of catppuccin to be enabled. Otherwise, the colors in the mason popup window clash with everything else.
=> feat(catppuccin): enable mason integration

lua/lazyvim/config/autocmds.lua
vim.api.nvim_win_set_cursor is expecting a window handle but was being passed the current buffer's handle instead
=> fix(autocmds): jump to last loc in buffer

lua/lazyvim/plugins/lsp/keymaps.lua
jump to existing window if buffer is already opened when the builtin.lsp_definitions, builtin.lsp_type_definitions and builtin.lsp_implementations only return one result.
https://github.com/nvim-telescope/telescope.nvim/pull/2454#event-9325221452
=> feat(lsp): add 'reuse_win' for reuse window in lsp definition keymap

lua/lazyvim/plugins/extras/lang/go.lua
@jyuan0 [noticed](https://github.com/LazyVim/LazyVim/pull/1115#issuecomment-1634975850) the null-ls sources are not installed by Mason. Figured I'd fix this in a separate PR.
=> feat(lang): add null-ls tools to mason's ensure_installed

lua/lazyvim/plugins/coding.lua, lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/ui.lua
This adds more detailed documentation strings to LazyVim's dependencies. As far as I can tell, the documentation for these on the website is generated from these docstrings.
This is just trying to add enough description so that people know what more of the plugins do without needing to click through to their individual sites.
=> Improve summary documentation of deps

lua/lazyvim/plugins/extras/lang/tex.lua
Here it is the support for `bib` and `tex` files mainly based on plugin [vimtex](https://github.com/lervag/vimtex) and LSP server [texlab](https://github.com/latex-lsp/texlab).
Some noticeable points are listed here:
1. Although treesitter provides highlights for `tex` files, vimtex renders better using conceal function. So I disabled the treesitter highlight for `tex` files. It will not affect the text-object function provided by treesitter.
2. For a better rendering result, vimtex requires to set `conceallevel` to 2 as written in line 34. It works fine without touching `<leader>uc`, which is defined in `config/keymaps.lua` as follows.
```lua
local conceallevel = vim.o.conceallevel > 0 and vim.o.conceallevel or 3
map("n", "<leader>uc", function() Util.toggle("conceallevel", false, {0, …
```
=> feat(lang): add tex support

lua/lazyvim/plugins/extras/lang/clangd.lua
It'd be nice if there was a precedence associated w/ the ordering of arguments, but I don't think there is and it seems to match the most nested dir. That's not ideal for a lot of projects, like [tree-sitter](https://github.com/tree-sitter/tree-sitter) where compile_flags.txt is in `lib/`
Suggestions welcome!
=> refactor: update clangd root detection

lua/lazyvim/plugins/extras/lang/java.lua
Main thing here is to use the more powerful https://github.com/mfussenegger/nvim-jdtls instead of the default setup provided by nvim-lspconfig.
Looking for early feedback like "yeah not interested go away"
Otherwise, it works but should do more to merge opts, prolly update some docs, that sort of thing.
=> feat(lang): add java

lua/lazyvim/plugins/extras/lang/go.lua
I'm getting an error with `<leader>td`, when I want to debug a go test. See https://github.com/LazyVim/LazyVim/discussions/1107 for details.
It seems there is no debug adapter defined in the Go extras. I can work around this locally like so:
```lua
return {
-- extend Go extras setup from lazy.lua, with DAP capability
{
"leoluz/nvim-dap-go",
dependencies = {
{ "mfussenegger/nvim-dap" },
},
ft = { "go" },
config = true,
keys = {
-- workaround, as nvim-dap-go does not have a DAP strategy set up for neotest
-- see https://github.com/nvim-neotest/neotest-go/issues/12
{ "<leader>tg", "<cmd>lua require('dap-go').debug_test()<CR>", desc = "Debug Nearest (Go)" },
},
},
}
```
...but I figured it might be better to extend the go extras with this capability, hence this PR.
- Add `nvim-dap-go` plugin. …
=> feat(lang): add debug adapter plugin for go

lua/lazyvim/plugins/editor.lua
Changes the current normal-mode mappings `<leader>sw` / `<leader>sW` to only display matches surrounded by word boundaries. Also adds the equivalent visual-mode mappings to allow searching for the current selection.
Selection searching does not consider word boundaries, so highlighting a single word and searching for it will produce the same results as the word-under-cursor searching did before this change. This allows the user to easily choose whether to include word boundaries in their search.
=> feat(telescope): allow word and selection searches

lua/lazyvim/plugins/extras/lang/python-semshi.lua, lua/lazyvim/plugins/extras/lang/python/semantic-highlight.lua
While cleaning up my config to use the new extras/lang/python, there is this one plugin that I think might be generally useful to many.
Since no python's lsp support semantic highlighting now or in the near future (pyright definitely won't), this is the best we can have for python.
The default color are hardcoded by semshi, so I either link it to matching semantic @lsp.... highlight group, or just add style and inherit the color defined by colorscheme.
Without semshi:
With semshi:
=> feat(python): add semantic highlighting

lua/lazyvim/plugins/extras/lang/cmake.lua
use `cmakelang` instead of  `cmakelint`, closes #1194
=> fix: #1194 use cmakelang instead of cmakelint

lua/lazyvim/plugins/lsp/init.lua
Updates the check for inlay hints support to use `supports_method` instead of `client.server_capabilities`, given that with dynamic registration checking for static server capabilities isn't enough:
=> fix(lsp): supports_method for checking inlay hint support

lua/lazyvim/plugins/extras/lang/yaml.lua
In YAML files LSP completion is not happening because yaml-language-server is failing with error:
TypeError: Cannot read properties of undefined (reading 'length')
from `out/server/src/languageserver/handlers/settingsHandlers.js:78:51`, which it's expecting to have `yaml.schemaStore.url.length` and it's doesn't exist.
Signed-off-by: Javier Tia <javier.tia@gmail.com>
=> lang: yaml: Fix TypeError undefined length

lua/lazyvim/plugins/extras/lang/clangd.lua
Hello,
I would like to remove the search for CMakelisits.txt in the clangd root directory, as discussed in #1165
The reason for this change is that projects following "modern" cmake convention contain multiple CMakelists.txt and are therefore not suitable for root directory detection.
Feel free to edit or comment
=> refactor(clangd): remove CMakelists from clangd root_dir search

lua/lazyvim/plugins/extras/lang/yaml.lua
`yamlls` settings is a bit different from `jsonls`. The `validate` property is just a boolean.
see https://github.com/redhat-developer/yaml-language-server#language-server-settings
=> Fix yaml validate and enable line folding

lua/lazyvim/plugins/extras/lang/python.lua
By default `venv-selector` only set virtual environment name to the `venv`. To be more versatile I've added more name possibilities.
=> feat(python): add more venv names

lua/lazyvim/config/keymaps.lua
While trying to disable `<C-s>` entirely by `vim.keymap.del({ "i", "v","n", "s" }, "<C-s>")` in my own `keymaps.lua`, I got an error on reopening Neovim `No such mapping`. After tinkering around a bit, I changed `v` to `x`, since `v` incorporates both `x` and `s` and the error stopped occuring.
=> Fix(keymaps): change `v` mode to `x` mode for `save file`

lua/lazyvim/plugins/extras/lang/java.lua
This is a replacement for #1300. It keeps the fixes from that PR:
1. Reverse dependency between `nvim-jdtls` and `nvim-lspconfig` so the former isn't loaded unnecessarily.
2. Enable cmp doc preview.
3. Use which-key to register all the keymap to avoid the unamed(+prefix) group.
4. Don't accumulate calls to `on_attach` for each java buffer opened.
5. Register keymaps and setup dap after the LSP fully attached.
and adds the following fixes:
1. Lazy load the plugin with `ft = { "java" }` but additionally handle the race condition internally by calling `attach_jdtls()` directly when the plugin loads.
2. Properly check whether debug is enabled with `Util.has("nvim-dap") and mason_registry.is_installed("java-debug-adapter")` (the original code in #1300 called `mason_registry.has_package()` …
=> fix(java): don't accumulate on_attach, and make more configurable

lua/lazyvim/plugins/extras/lang/java.lua
Support setup nvim-dap config in Java by launch.json, if there is no `.vscode/launch.json`, nothing will happen, so no side effect
It's convenient to generate dap configurations by VsCode
Related: https://github.com/mfussenegger/nvim-dap/pull/48
=> feat(java): support vscode launch json in Java

lua/lazyvim/plugins/editor.lua
When adding mappings to Telescope with anonymous functions, the following notification is shown when invoking Telescope's which-key:
The fix is to replace the anonymous functions by references to named ones, as described in [this comment](https://github.com/nvim-telescope/telescope.nvim/issues/2237#issuecomment-1322642896).
=> fix(telescope): replace anonymous functions in mappings by named functions

lua/lazyvim/plugins/extras/lang/python.lua
Fixes #1528 kind of. It makes sense that if you want to debug, you'd also need to install `DAP Core`, but this PR is mostly so that venv-selector `dap_enabled` option is in accordance with `nvim-dap` spec in Python extra configuration and since the latter is `optional`, I believe it makes sense that `dap_enabled` should also be conditional on the existence of `nvim-dap-python`.
=> fix(python): make venv-selector `dap_enabled` conditional on `nvim-dap-python`

lua/lazyvim/plugins/extras/lang/elixir.lua
(sorry, sent the PR without the description by mistake)
Credo is the de-facto linter for Elixir. I was not aware that null-ls already had Credo as a builtin before, so that's an easy addition for folks already using null-ls.
btw, LazyVim was recently mentioned in ElixirForum:
https://elixirforum.com/t/neovim-elixir-setup-configuration-from-scratch-guide/46310/35
=> feat(elixir): Add credo if none-ls is used

README-CN.md
See: https://github.com/LazyVim/LazyVim/commit/bfe04222fe5585179f03197b01a6f6ed711d4421
=> docs!: LazyVim now requires Neovim >= 0.9.0

lua/lazyvim/plugins/ui.lua
See lukas-reineke/indent-blankline.nvim#665.
Without patch:
With patch:
=> fix(indent-blankline): set `config.indent.tab_char`

lua/lazyvim/plugins/extras/lang/rust.lua
For https://github.com/Saecki/crates.nvim/commit/57c448bffacba1d7970afc2823b9d30e7cecf516:
```
* fix!: nvim-cmp source registration
BREAKING CHANGE: the nvim-cmp source isn't automatically registered
anymore. Instead enable it in setup.
require("crates").setup {
src = {
cmp = {
enabled = true
},
},
}
```
=> fix(rust): explicitly enable nvim-cmp source registration for crates

lua/lazyvim/plugins/ui.lua
to update context on "CursorHold" instead of of using default "CursorMove"
=> perf: enable lazy_update_context option

lua/lazyvim/plugins/coding.lua, lua/lazyvim/plugins/extras/coding/codeium.lua, lua/lazyvim/plugins/extras/coding/copilot.lua
**nvim-cmp** has a `group_index` property that we used incorrectly in LazyVim, resulting in only showing entries from the first group that had entries.
This lead to several issues with different sources like copilot.
Probably fixes a number of issues at `copilot-cmp`:
For instance, you can set the `buffer`'s source `group_index` to a larger number
if you don't want to see `buffer` source items while `nvim-lsp` source is available:
```lua
cmp.setup {
sources = {
{ name = 'nvim_lsp', group_index = 1 },
{ name = 'buffer', group_index = 2 },
}
}
```
You can also achieve this by using the built-in configuration helper like this:
```lua
cmp.setup {
sources = cmp.config.sources({
{ name = 'nvim_lsp' },
}, {
{ name = 'buffer' },
})
}
```
=> fix(cmp): properly set cmp group_index

lua/lazyvim/plugins/extras/formatting/black.lua
Just like [prettier format](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/formatting/prettier.lua), it would be nice if there was a similar one for black.
=> feat(black): added an extra for black with null-ls

lua/lazyvim/plugins/extras/formatting/black.lua
conform.nvim doesn't actually have a config for `blackd`.
=> fix(black): remove unknown blackd from conform

lua/lazyvim/plugins/editor.lua
Very useful when use with edgy and when to collapse other sections of the bar.
Same keymap pattern fe, ge, be -> files, git, buffers explorer
=> feat(nvim-tree): add keymaps toggle git & buffer

lua/lazyvim/plugins/extras/lang/go.lua
After https://github.com/LazyVim/LazyVim/pull/1535 and https://github.com/LazyVim/LazyVim/pull/1549, some formatters (i.e.: `gofumpt`) were removed from the `conform.nvim` and `none-ls.nvim` configurations in `extras.lang.go` because they were already already handled by the LSP `gopls`.
With the release of LazyVim 10.0.0, only one formatter can be active at a time so `gopls` is no longer taking care of running `gofumpt` when `conform` or `none-ls` are active.
This PR adds it back to the `conform.nvim` and `none-ls.nvim` configurations so people using any of the two can use `gofumpt`. This PR also makes sure packages are only installed when strictly necessary: for example, `delve` is only needed when `nvim-dap` is available and `gomodifytags` and `impl` are not supported by conform since …
=> feat(go): add gofumpt formatter with conform/none-ls

lua/lazyvim/config/keymaps.lua, lua/lazyvim/plugins/lsp/keymaps.lua
Sometime, a buffer has a linter but does not have lsp attached (e.g bash/zsh file with shellcheck only). Some diagnostic keymaps are not available in those case since they are registered with LSP only.
I propose to move diagnostic keymaps to the more general keymaps file similar to formatting and inlay_hint functionality.
=> fix(keymaps): no diagnostic keymaps w/o lsp attached

lua/lazyvim/plugins/extras/ui/edgy.lua
Title could also be `Search/Replace`, because the Spectre panel shows *Nvim Spectre* in the panel as well.
=> fix: add title to Spectre panel in edgy

lua/lazyvim/plugins/linting.lua
Add ability to configure a linter to run either for all filetypes or as a fallback if no others are configured.
- https://github.com/LazyVim/LazyVim/issues/1726
=> feat(linting): ability to configure global and fallback linters

lua/lazyvim/plugins/extras/lang/markdown.lua, lua/lazyvim/plugins/extras/lang/python.lua
1. Add `ft = "python"` to the `nvim-dap-python` keymaps.
2. Remove "Peek" from the `MarkdownPreviewToggle` description.
=> Add `ft` to Python keymaps, and fix "Markdown Preview" toggle description

lua/lazyvim/plugins/ui.lua
We can use the git diff info from gitsigns in lualine. Anyway, it exists and can be configured to handle worktrees ($GIT_DIR other than .git)
=> feat(lualine): use gitsigns for diff source

lua/lazyvim/plugins/extras/coding/tabnine.lua
add the `:CmpTabnineHub` command to the build process, similar to copilot and codeium
=> fix(tabnine): run `:CmpTabnineHub` automatically on build

lua/lazyvim/plugins/extras/lang/typescript.lua
Previously used typescript.nvim for this (`:TypescriptRemoveUnused` or somesuch)
Not sure if `<leader>cR` is the best binding but it seems reasonable. I like caps for stuff that's destructive.
=> feat(typescript): remove unused imports

lua/lazyvim/plugins/extras/util/project.lua, lua/lazyvim/plugins/ui.lua
Referencing this [PR](https://github.com/LazyVim/LazyVim/pull/1791)
@folke,
The p from extras.util.project still contained the brackets.
=> style(dashboard): remove unnecessary brackets from keys, including extras

lua/lazyvim/plugins/extras/util/mini-hipatterns.lua
'mini.hipatterns' now [implements `extmark_opts`](https://github.com/echasnovski/mini.nvim/blob/35e29f7d680cfeb496415cadadd8c1f68db759b9/doc/mini-hipatterns.txt#L286-L291) for more possibilities of adding highlights (like highlighting whole line, adding signs, overlayed/right-aligned/inline virtual text, etc.). The `priority` highlighter options is silently soft deprecated with soon to issue `notify_once()` if user uses it. Decided to make a good did and not annoy many people using it through LazyVim :)
Notes:
- This would require 'mini.hipatterns' with at least [this commit](https://github.com/echasnovski/mini.hipatterns/commit/245497df55a180a289de00510c2ffe5b7bbaa5b2).
- The `gen_highlighter.hex_color()` will continue to use `priority` as it won't export much configuration via …
=> fix(mini.hipatterns): use `extmark_opts` instead of soft deprecated `priority`

lua/lazyvim/config/keymaps.lua
Some of us using alternate keyboard layouts (e.g. Colemak-DH) may rely on arrows instead of `j/k`. This extends the `j/k` enhancements for soft-wrapped lines navigation to the `<Up>/<Down>` arrows as well.
I'm a total vim noob, any reason I shouldn't do this?
=> feat(nvim): extend j/k enhancements to up/down arrows

lua/lazyvim/plugins/extras/lang/cmake.lua
1. mason/cmakelang install bin/cmake-lint
2. nvim-lint only recognize bin/cmakelint
3. mason/cmakelint install bin/cmakelint
so we need mason/cmakelint installed to using nvim-lint to perform formatting
=> fix(lang): add cmakelint to ensure installed list

lua/lazyvim/config/keymaps.lua, lua/lazyvim/plugins/lsp/init.lua, lua/lazyvim/util/lsp.lua, lua/lazyvim/util/toggle.lua
Neovim introduced a breaking change to how inlay-hints were handled in [448907ff](https://github.com/neovim/neovim/commit/448907f65d6709fa234d8366053e33311a01bdb9). Check to see if the user is using nightly and if so use the newly added `.enable` method.
=> Detect if using nvim-0.10 and use new inlay_hint.enable method

lua/lazyvim/plugins/lsp/init.lua
As of [8122470](https://github.com/neovim/neovim/commit/8122470f8310ae34bcd5e436e8474f9255eb16f2) diagnostic signs are configured using `vim.diagnostic.config`. This adds the signs to the diagnostic options that are passing to the diagnostics config.
=> Add diagnostic signs to lsp options

lua/lazyvim/plugins/extras/test/core.lua
Useful to run the same test on a different file.
=> Add <leader>tl to neotest.run_last()

lua/lazyvim/config/keymaps.lua
Added a function in the ui menu to toggle between light and dark background themes. Helpful for themes like 'gruvbox' where color schemes are in one package and can't be changed with the theme switcher menu, but also works with other themes that support it.
I find this useful so I wanted to share in case someone else might too.
=> feat(ui): add function to toggle between light/dark backgrounds

lua/lazyvim/plugins/extras/linting/eslint.lua
The eslint LSP has changed one of the setting names from `workingDirectory` to `workingDirectories`.
See its documentation [here](https://github.com/microsoft/vscode-eslint/blob/17e79c0f7bcd38f3033d0fbc346a5607fbb4c60f/README.md?plain=1#L218).
=> fix: correct eslint working directories setting

lua/lazyvim/plugins/editor.lua
I was missing an easy way to copy the file name from within the Neo-Tree window. I think others might find this useful and wanted to contribute :)
This PR simply adds the suggestion [here](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/359#issuecomment-1164667350).
Thank you!
=> Adds copy file name command to Neo-Tree with 'Y' binding

lua/lazyvim/config/autocmds.lua
It triggered an 'E11: Invalid in command-line window; <CR> executes,
CTRL-C quits' error when Neovim was in Command Line window and
FocusGained.
=> fix(autocmds): avoid checktime when buftype=nofile

lua/lazyvim/plugins/extras/lang/typescript.lua
This started as an attempt from me to change the `shiftwidth` value for `.js` files in order for the `tsserver` to format the files using the new value.
However, that didn't seem to work. I tried to make the change both in `after/ftplugin/javascript.lua` and with an auto command on `FileType/BufReadPost` events. None of them worked, `tsserver` continued to format with the value of `shiftwidth` it would read from `options.lua`. I didn't want to change the top-level value of `shiftwidth` in `options.lua` (as I generally prefer it that way for the rest of my LazyVim usage). The other way would be to manually override the values of `tsserver` format settings in my personal `lspconfig` configuration.
My first attempt (first commit) was to change the `opts` into a function, so that the values …
=> fix(typescript): don't hardcode values in lua table

lua/lazyvim/plugins/extras/util/dot.lua
Hey @folke,
Apologies for the noise in #2330. I've double-checked the `tree-sitter-hyprlang` setup for Neovim users. It appears that the parser declaration is happening after Tree-sitter's initialization [init.lua](https://github.com/luckasRanarison/tree-sitter-hyprlang/blob/master/plugin/init.lua), preventing the Hyprlang parser from being installed during the install step. To address this, I've created this PR to leverage LazyVim's approach for Tree-sitter installation.
Please let me know if you have any questions or concerns.
Thanks!
=> fix(hyprlang): use lazyvim way to install

lua/lazyvim/plugins/extras/lang/rust.lua
For example, 'buffer' source by default has group_index = 2 [1], however
if we take all the sources plus crates and run them through
cmp.config.sources() again, since it's a one-dimensional list, all
group_indexes will be reset to 1.
[1] https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/plugins/coding.lua#L74-L80
=> fix(rust): avoid resetting cmp group_index to 1

lua/lazyvim/config/autocmds.lua
A recent commit added an auto command to set `conceallevel` to 0 (show normally) for JSON files. The issue is that this is applying the change at the window level. So other file types (like markdown) are also affected after a JSON file is opened. The proposed change is to apply the change to the local buffer options. This will preserve the default `conceallevel` set in both the LazyVim and user options.
Restrict changes to `conceallevel` to the desired file types.
Applied this change to my local configuration and opened up both json and markdown files to confirm that the desired conceal level is being applied.
=> fix(autocmds): apply conceal level change to local buffer options

lua/lazyvim/plugins/extras/util/dot.lua
hyprlang grammar is now included in nvim-treesitter and the plugin itself has been removed from the tree-sitter-hyprlang repo, so I've updated the file accordingly.
=> fix(dot): remove hyprlang plugin

lua/lazyvim/plugins/editor.lua
It copies the path of the file/directory
I was confused by the `"Y" : <function>` tooltip in neo-tree
=> Add description to "Y" in Neo-Tree

lua/lazyvim/config/autocmds.lua
Proposed fix for #2593
Also, close-with-q is default for man-files in Neovim [1]. No need to fix this with a custom binding.
1: <https://github.com/neovim/neovim/blob/master/runtime/ftplugin/man.vim#L28>
=> nvim already binds q to close for man-files

lua/lazyvim/config/options.lua
Avoid lowering timeoutlen when running in VS Code, to avoid unwanted timeouts from key mappings.
The lower value of 300ms (down from Neovim's default of 1000ms) works great outside of VS Code, where it helps trigger the which-key UI quickly, and where which-key prevents timeouts from occuring.
But in VS Code (where which-key isn't applicable), the lower value makes it difficult to perform some key mappings in time, such as `]p`, which requires shifting hand position.
=> fix(options): don't lower timeoutlen when in VS Code

lua/lazyvim/plugins/extras/coding/yanky.lua
When directly modifying its `enabled` property, the plugin will remain disabled even if required by another plugin.
=> fix(yanky): properly disable sqlite.lua on Windows

lua/lazyvim/plugins/extras/util/mini-hipatterns.lua
Shorthand hex colors will have a matching background color. For example, `#f00` will have a red background.
I'm not very experienced with hipatterns' API. If anything at all can be done in a better way, please let me know.
=> feat(hipatterns): add shorthand hex color support

lua/lazyvim/plugins/extras/lang/ansible.lua
Additionally I used to create such autocommand to set proper filetype on ansible files.
```lua
-- Set proper filetype for ansible files
vim.api.nvim_create_autocmd({ "BufNewFile", "BufRead" }, {
pattern = {
"*/playbooks/*.yml",
"*/playbooks/*.yaml",
"*/roles/*/tasks/*.yml",
"*/roles/*/tasks/*.yaml",
"*/roles/*/handlers/*.yml",
"*/roles/*/handlers/*.yaml",
},
callback = function()
vim.bo.filetype = "yaml.ansible"
end,
})
```
Maybe there is any other way to set proper filetype.
=> feat(lang): add ansible support

lua/lazyvim/plugins/extras/editor/outline.lua
Recently `symbols-outline.nvim` has been achieved, so use `outline.nvim` instead with more features.
=> feat: use outline.nvim instead of symbols-outline.nvim

lua/lazyvim/util/ui.lua
Fixes #2540 by showing the effective definition instead of the linked group name.
=> fix(util.ui.fg): Add `link=false` to show effective definition

lua/lazyvim/plugins/extras/lazyrc.lua, lua/lazyvim/plugins/xtras.lua
The motivation for this PR can be found in this [discussion](https://github.com/LazyVim/LazyVim/discussions/1878), started by @fredrikaverpil.
Quote:
> I really wish I could add some sort of lazy.nvim override in the project's .nvim.lua. Doesn't seem possible to me though.
It is possible to configure project-specific settings using a local `.nvim.lua`. However, out of the box,`.nvim.lua` cannot add to the spec used by `lazy.nvim`.
This [comment](https://github.com/LazyVim/LazyVim/discussions/1878#discussioncomment-7667560) describes a solution using the local `.nvim.lua` to bootstrap `lazy.nvim`.
That approach has the following drawbacks:
1. The user has to slightly modify the structure of his config
2. The `setup` function for `lazy.nvim` can now be in several places
3. Local …
=> feat(extras): Enable project-specific plugin specs using local .lazy.lua

lua/lazyvim/plugins/extras/lang/java.lua
[1] https://github.com/mfussenegger/nvim-jdtls/blob/382b9f625861f47d95876bcfb4c261f3b96077cb/doc/jdtls.txt#L206-L210
---
Personally I needed this to configure different dap_main environment variables.
=> feat(java): allow opts for setup_dap_main_class_configs()

lua/lazyvim/plugins/extras/lang/go.lua
Adding opts recursive_run to fix the error `no Go files in /path/project`. This issue is caused by a recent change in the `nvim-neotest/neotest-go` project, which now [defaults to non-recursively](https://github.com/nvim-neotest/neotest-go/pull/72)
=> fix(go): adding opts recursive_run

lua/lazyvim/util/root.lua
This PR clean up the buffer root dir cache also when CWD changes.
This issue happens when the CWD changes by using a cd command while inside a file or netrw buffer (or oil.nvim buffer). Then the LazyRoot command output does not coincide to the value inside the root dir cache if the root spec was using cwd option.
Not sure if this is the correct way to fix this case. But when using oil.nvim I found out that changing the CWD while inside oil buffer does not change the lazy root hence telescope find files returned files from another dir.
=> fix(util): clear buffer root cache when cwd change

lua/lazyvim/plugins/extras/lang/haskell.lua
The `haskell-snippets.nvim` plugin wasn't being lazy loaded and was increasing my neovim startup time by 100ms.
- Added `ft = { <haskell_files> }` so it lazy loads only when entering a Haskell file.
- Also formatted the file
=> Make Haskell-snippets lazy load for performance

lua/lazyvim/plugins/extras/lang/terraform.lua
The commentstring for terraform and HCL files is now handled by nvim-ts-context-commentstring:
https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/94
This PR replaces https://github.com/LazyVim/LazyVim/pull/2526.
Credit to https://github.com/reegnz
=> fix(terraform-extra): Drop unnecessary commentstring config for terraform

lua/lazyvim/util/lualine.lua
Adds two additional options to pretty_path: `filename_hl` and `dirpath_hl`.
This allows users to customize the highlight group of both the directory component of the path name and the filename independently. modified_hl is still used when the buffer has been modified. 
This commit does not change LazyVim's default formatting of the lualine path name segment. 
Lazy's default:
With the new options:
When the buffer has been modified:
But, now users can achieve the above by passing the options to `pretty_path`:
```lua
local util = require("lazyvim.util")
return {
{
"nvim-lualine/lualine.nvim",
opts = function(_, opts)
opts.sections.lualine_c[4] =
{ util.lualine.pretty_path({ filename_hl = "Bold", modified_hl = "MatchParen", dirpath_hl = "Conceal" }) }
return opts
end,
},
}
```
Thanks to …
=> feat(lualine): add more hl options to pretty_path

lua/lazyvim/config/keymaps.lua
This adds the `<leader>gf` (for Git File) keymap that lets you view commit history for the current file.
Lazygit supports this through their CLI (see [doc](https://github.com/jesseduffield/lazygit/blob/fd18db6ba285eb280aee1cb8c381295df6556cad/docs/Searching.md?plain=1#L20)) with a `-f <filepath>` flag which must be a path to the file from the git dir.
Looks like this:
Open to suggestions on different keymap or implementation
=> feat(git): add <leader>gf for lazygit commit history on current file

lua/lazyvim/plugins/extras/lang/rust.lua
Hey :wave: 
A way to override rustaceanvim's settings per project is by using `:h exrc`.
This doesn't appear to work with LazyVim (see https://github.com/mrcjkb/rustaceanvim/issues/283), likely because it overwrites `vim.g.rustaceanvim` the settings in the `config` function.
This should fix that.
=> fix(lang/rust): don't overwrite `vim.g.rustaceanvim` if it is defined

lua/lazyvim/plugins/formatting.lua, lua/lazyvim/util/lsp.lua
Inspired by #2615, I thought this might be a good change hopefully.
Not 100% sure if this breaks anything else (though I tested it locally and seemed to work correctly), since I'm not that familiar with LazyVim formatting in depth, thus starting as a draft.
=> fix(conform): make `lsp_fallback` option user configurable

lua/lazyvim/plugins/extras/editor/mini-files.lua
If you press `g` in a mini.files menu, the `.` key shows up but doesn't have a description. This adds a desc attribute to the binding so the menu shows a correct description.
=> Description for `g.` keybinding in mini.files

lua/lazyvim/plugins/editor.lua
noticed, that the group description for folds was `+prefix`. I added a fix to set the description to `+fold`
=> fix(which-key): add group description for folds

lua/lazyvim/config/keymaps.lua
use compatible function for windows and linux for keybinding `<leader>gf`.
Fixes #2735
=> fix(git): compatible function

lua/lazyvim/plugins/extras/dap/core.lua, lua/lazyvim/plugins/extras/test/core.lua
neotest now requires nvim-neotest/nvim-nio to be
installed as per BREAKING CHANGE: https://github.com/nvim-neotest/neotest/pull/337
=> Adding required nvim-nio to test and dap extra (neotest and nvim-dap-ui respectively)

lua/lazyvim/util/lualine.lua
Closes #2752
I left the initial text blank on purpose, so that it doesn't change anything stylistically and let the user decide what he wants to add in his personal configuration for `lualine` spec.
=> feat(lualine): add `modified_sign` to `pretty_path`

lua/lazyvim/plugins/formatting.lua
Some formatters like styler take a while to format (2s). They fail to format when run on injected code. This should help fix that :).
=> fix: format injected langs does not wait 300ms

lua/lazyvim/plugins/coding.lua
Proposing to add some more text objects I've been using quite frequently for a while.
These are all examples from the mini.ai document itself.
- `d` for digits, matches consecutive digits
- `e` because it's near `w`, for subword in camelCase and snake_case
- `g` for entire buffer, similar motion to `gg` and `G`. For example, now `dag` instead of `ggdG` or `ggvGd` will delete entire buffer.
- `u` for "Usage", to selection function and method call since `f` and `c` is already taken for function definition.
- `U` similar to `u`, but match without dot in function name
=> feat(mini.ai): add more objects d,e,g,u,U

lua/lazyvim/plugins/formatting.lua, lua/lazyvim/util/lsp.lua
Since `Util.merge` performs an **in-place** merge, `bufnr` is being leaked into the opts tables before being sent to the formatter.
This causes, in rare cases, the `bufnr` to be **replaced** by the wrong `bufnr` (i.e, not the current buffer), causing the formatting to apply to the wrong file.
This bug caused random text to be copied and inserted into unrelated files on save, which eventually snuck into our QA environment. Luckily, it got caught and I started investigating the issue. I found that the issue happened after ([afca0b7](https://github.com/LazyVim/LazyVim/commit/afca0b7876abf9022ee0754270f603e981ea42a5)), and found the root cause.
To demonstrate why this is a problem, do as follows:
- Open an arbitrary file and save it, triggering conform
- Note which `bufnr` this has via `:echo …
=> fix(format): Don't leak bufnr into opts tables

lua/lazyvim/plugins/editor.lua
This adds the "O" mapping to Neo-tree to open the file in the system default app. I found this really useful for opening things like directories in the default file explorer, or images/pdfs since the terminal can't render those. There is an open [issue](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1224) in neo-tree but it's been labelled as wontfix so I think adding this to something like LazyVim is a good idea.
Let me know if you need me to add anything.
=> feat(neo-tree): add mapping "O" to open with system default

lua/lazyvim/plugins/extras/editor/mini-move.lua
The main motivation for using mini.move instead of the native move command is to avoid polluting the undo history as mini.move allows undoing consecutive moves with one single `u`. And horizontal moves are nice too!
I set up the keybindings manually to overwrite the default keymaps, as well as to set up moving in InsertMode.
=> feat(extras): propose to add mini.move as an extra instead of native move command

.github/workflows/ci.yml
Since Node.js 16 actions are deprecated, updating the actions to use Node.js 20 is recommended. All actions in `ci.yml` have a newer version; this change bumps the actions to subsequent versions. A sample warning is provided below:
=> ci: update action versions to remove node warning

lua/lazyvim/plugins/extras/lang/python.lua
Use the new builtin rust-based `ruff server` instead of the python-based `ruff_lsp` wrapper.
Ruff_lsp is not deprecated (yet) but the new rust-based server is faster and is (almost?) feature complete.
Though it's still in beta, it has been highlighted in the latest [ruff release](https://github.com/astral-sh/ruff/releases/tag/v0.4.0) and it has worked well for me for a while.
=> feat(python): use new `ruff` instead of `ruff_lsp`

lua/lazyvim/plugins/extras/editor/harpoon2.lua
When adding a new file with `<leader>H` a new message pops-up with please use add instead of append. 
Also when removing a file from the harpooned files list without command `:wq` the file list is not updated. That behaviour is corrected with the `save_on_toggle = true` flag.
=> fix(config): harpoon2 deprecated message 

lua/lazyvim/plugins/extras/util/dot.lua
previous `.*/kitty/*.conf` can only match two kind of file: `kitty.conf` and `kitty/.conf`
=> fix(dot): can't match kitty conf file

lua/lazyvim/plugins/extras/util/dot.lua
Assign `opts.ensure_installed` first because if it were to be nil, I believe that it would not be assigned nor extended with shellcheck.
Remove shfmt since LazyVim sets it up by default.
=> fix(dot): install when list is empty

lua/lazyvim/config/keymaps.lua
Really minor change.
Make the warning more clear on what "THIS" is -- LazyVim.safe_keymap_set.  Because when I saw this, it wasn't clear to me what I need to do.
I saw `local map = vim.keymap.set` in someone else's config.
=> Say "local map =" in the comment under DO NOT USE THIS!

lua/lazyvim/plugins/extras/coding/native_snippets.lua
According to this commit [#2856](https://github.com/neovim/neovim/pull/28560) of neovim , fix native_snippets.
=> Fix native_snippets for vim.snippet api changes

lua/lazyvim/plugins/extras/lang/rust.lua
I saw the official manual said this. I thought our configuration was wrong. I fixed it.    
rust-analyzer manual:  
https://rust-analyzer.github.io/manual.html#nvim-lsp
=> fix(extras): Rust-Analyzer cargo option

lua/lazyvim/plugins/extras/lang/python.lua
Provide global variable to choose between `ruff` and `ruff_lsp` in accordance to `pyright`/`basedpyright`.
Pinging @arafune for #3057. Are you ok with something like this, so that users can decide which one to use? 
By default, `ruff_lsp` is used unless the user explicitly chooses `ruff` instead. If you would like to incorporate these changes
to your PR yourself, I don't have any problem closing this.
=> fix(python): make both `ruff` and `ruff_lsp` available to user

lua/lazyvim/plugins/ui.lua
As https://github.com/nvimdev/dashboard-nvim/pull/450, dashboard-nvim shouldn't be lazy-loaded to properly handle stdin.
Not really sure if this is enough to make dashboard-nvim not lazy-loaded.
=> fix(ui): don't lazy-load dashboard-nvim

lua/lazyvim/plugins/editor.lua, lua/lazyvim/util/root.lua
After taking another look at #3088 and #3090, I remembered another issue about Neo-tree, which used an autocommand to lazy-load it instead of directly requiring it at startup (see [this comment](https://github.com/LazyVim/LazyVim/discussions/2366#discussioncomment-8156257)). 
I then tested again with the initial LazyVim implementation in `init` function and saw that when you do `nvim some_directory/`, then it opens 2 buffers (neo-tree on the left and an empty unnamed buffer on the right). I did `verbose pwd` on both buffers and I saw different results. neo-tree buffer had `[tabpage] some_directory` (the same as the file argument passed when invoking nvim with a directory), but the empty unnamed buffer had `window current_working_directory` (the directory where Neovim was invoked from). …
=> fix(neo-tree): correctly set up `cwd`

lua/lazyvim/plugins/lsp/init.lua
In `mason-lspconfig` you can specify versions of packages to be installed (i.e eslint@4.8.0). The current `ensure_installed` in `lsp/init.lua` doesn't take that into account, rather only populates `local ensure_installed` with the server names declared in `nvim-lspconfig`. 
This change makes it possible to also take into account the `opts.ensure_installed` of `mason-lspconfig.nvim` in case users want to declare specific versions of packages to be installed.
=> feat(mason-lspconfig): allow `opts.ensure_installed` to be taken into account

lua/lazyvim/plugins/extras/lang/rust.lua
Recent changes to create.nvim displayed warning.
https://github.com/Saecki/crates.nvim/pull/120
Renamed `src` to `completion`
=> fix(extras.lang.rust): creates.nvim src option was renamed to completion

lua/lazyvim/util/plugin.lua
Fixes #2891 (potentially)
After I saw that issue after a long a time, I decided to take a deeper dive to how `lazyfile` works. 
Unfortunately, with my lack of programming experience, I could only understand some things on the surface, so I ended up doing some `vim.print` to have some visual hints. I then noticed that `filetypedetect` was given back from `Event.get_augroups(event.event)` and included in the `skips` table, which is later excluded in `Event.trigger`. 
My assumption was that due to `filetypedetect` being skipped, the filetypes added in `extras.util.dot` could not be detected in `LazyFile` event when Neovim was invoked with file arguments, as also stated in the aforementioned issue.
So, I just tried to exclude `filetypedetect` from being added to `skips` table and when I …
=> fix(lazyfile): exclude `filetypedetect` from skips

lua/lazyvim/plugins/extras/lang/ansible.lua
If lazy extras yaml is enabled, yamlls was being loaded not ansiblels.
Add `ft = {}` to nvim-ansible spec allows `ft=yaml.ansible` to be detected.
Re-mapped nvim-ansible plugin key to not conflict with neotest.
Added a description for the keymap.
=> fix(ansible): ansiblels not loading, neotest keymap conflict

lua/lazyvim/plugins/extras/lang/clangd.lua
The attribute name for picked process id when attaching the debugger is `pid`, not `processId`.
https://github.com/vadimcn/codelldb/blob/master/MANUAL.md
=> update the attribute name for process ID

lua/lazyvim/plugins/extras/dap/core.lua
This seems to be the proper fix for #1503. jsonc ensures compatibility with native vscode.
Ref: https://github.com/mfussenegger/nvim-dap/issues/964
=> fix(dap): load vscode launch files with jsonc parser

lua/lazyvim/plugins/extras/lang/terraform.lua
Ensures `tflint` (terraform linter) is installed when `lazyvim.plugins.extras.lang.terraform` is enabled
=> feat(terraform): ensure tflint is installed

lua/lazyvim/plugins/extras/lang/typescript.lua
`"pwa-"` prefixed debug types are deprecated in the debug adapter. ref: https://github.com/microsoft/vscode-js-debug/pull/1305
Also, vscode generates launch.json files with `"type": "node"` by default now, and warns if we use `"pwa-node"`
This PR adds support for `"node"` dap adapter/debugtype which maps to `"pwa-node"`. This behaviour is same as of the upstream debug adapter's supporting extension
=> fix(extras.lang.typescript): support `node` debug type along with `pwa-node`

lua/lazyvim/config/keymaps.lua
j/k are shown correctly but I added a description anyways for consistency
=> fix(keymaps): better up/down keymaps description

lua/lazyvim/config/autocmds.lua
I fixed this before in #473 but maybe it was accidentally reintroduced. I can understand the benefits of being able to just use q to close the query editor, but query *files* (those in nvim-treesitter or any tree sitter repository) are actual files and become very annoying to edit with this shortcut if i accidentally hit q
=> fix(autocmds): remove query from q-to-quit autocmd

lua/lazyvim/plugins/editor.lua
https://github.com/lewis6991/gitsigns.nvim/commit/59bdc1851c7aba8a86ded87fe075ef6de499045c
Update deprecated functions, and add two keymaps to move to first and last hunk.
=> fix(gitsigns): update deprecated hunk nav mappings

lua/lazyvim/plugins/extras/dap/core.lua
The .vscode/launch.json detection added in https://github.com/LazyVim/LazyVim/pull/1839 doesn't support many filetypes
This adds the support of debug adapter to file types mappings.
=> fix(dap): add debugger to filetypes mapping for launch.json

lua/lazyvim/plugins/extras/ui/treesitter-rewrite.lua
fix error `...Vim/lua/lazyvim/plugins/extras/ui/treesitter-rewrite.lua:11: attempt to index global 'Config' (a nil value)`
=> fix(treesitter-rewrite): add missed local Config

NEWS.md
=> fix(news.md): fix typo in native snippets announcement

lua/lazyvim/util/toggle.lua
`is_enabled` also accepts a `filter` and when we initially toggle `inlay_hints` on [here](https://github.com/LazyVim/LazyVim/blob/735f5905f85fec0dd5210f2c835597caa5a409fb/lua/lazyvim/plugins/lsp/init.lua#L153), we pass a `bufnr` which sets the `inlay_hints` in the `bufstate` (see [here](https://github.com/neovim/neovim/blob/42aa69b076cb338e20b5b4656771f1873e8930d8/runtime/lua/vim/lsp/inlay_hint.lua#L407-L432)), but when we call `is_enabled` without a filter table the returned result if from the `globalstate` (see [here](https://github.com/neovim/neovim/blob/42aa69b076cb338e20b5b4656771f1873e8930d8/runtime/lua/vim/lsp/inlay_hint.lua#L376-L388)). With `inlay_hints` toggled on by default you have to press `<leader>uh` twice to toggle them off without this change.
=> fix(util.toggle): correctly toggle `inlay_hints`

lua/lazyvim/plugins/extras/editor/refactoring.lua
This adds a missing label for the key group in the refactoring extra.
=> fix(refactoring): add label to refactoring key group

lua/lazyvim/plugins/extras/editor/leap.lua
This adds a missing label for the remapped surround key group in the leap extra.
I was considering adding `["gs"] = { }` to the mappings, but I wasn't certain if this would be necessary or correct for removing the original `gs` key group (which doesn't appear in which-key anyway).
=> fix(leap): add label to renamed surround mappings key group

NEWS.md
The previous wording was a little clunky (disable disabling). This removes the double negative.
=> Clarify vim.g.deprecation_warnings behavior

lua/lazyvim/util/lazygit.lua
**Example:**
I want to blame line 44 of file `myfile`.
**Current behavior:**
`cmd` will be `git log -n 3 -u -L 43,+1:myfile`, so I get the blame for line 43 instead.
=> fix(lazygit): Fix off-by-one issue in blame_line

lua/lazyvim/plugins/extras/coding/yanky.lua
Currently, yanky is only loaded on yank and put operations. This is problematic because if you open a file and start deleting lines (`d<motion>`), you lose them because yanky is not loaded to save them.
=> fix(yanky): load yanky earlier to avoid losing deleted lines

lua/lazyvim/plugins/extras/lang/toml.lua
adding toml support to PR on LazyVim
tree-sitter: toml
mason: taplo
conform: taplo
nvim-lint: taplo
originally here: https://github.com/LazyVim/LazyVim/pull/2883
=> feat(lang): add toml

lua/lazyvim/plugins/ui.lua
Pin is no longer needed as bufferline added 0.9.x compatibility.
=> fix(bufferline): unpin bufferline with 0.9.x compatibility

lua/lazyvim/plugins/extras/vscode.lua
Enable dial.nvim, yanky.nvim, and mini.move, all extras which are compatible with vscode.
=> feat(vscode): enable more compatible plugins

lua/lazyvim/plugins/extras/lang/kotlin.lua
Adding kotlin support
---
1. `mason`
- [ktlint](https://github.com/pinterest/ktlint)
- [kotlin-language-server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#kotlin_language_server)
- [kotlin-debug-adapter](https://github.com/fwcd/kotlin-debug-adapter)
---
2. `tree-sitter`
- kotlin
---
3. `nvim-lspconfig`
- kotlin-language-server
---
4. `nvim-lint`(optional)
- ktlint
---
5. `conform`(optional)
- ktlint
---
6. `none-ls`(optional)
---
7. `nvim-dap`(optional)
- [kotlin-debug-adapter](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#kotlin)
---
8. mini.comment/nvim-ts-context-commentstring
- I also opened a [pr](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/104) for kotlin support in …
=> feat(extras.lang): Add kotlin

lua/lazyvim/plugins/extras/lang/python.lua
Update the Python extra for the `linux-cultist/venv-selector.nvim` plugin so that the key map to select a virtual environment is only present (in which-key) when the filetype of the buffer is `python`.
This is mostly a nice UI thing for when I'm not working in a Python project, so that which-key doesn't show me an option that is not currently relevant.
=> fix: extras.lang.python to enable venv select keys on ft

lua/lazyvim/util/lsp.lua
When getting `buffer` from `client.attached_buffers` with `ipairs`, the loop and the `LspDynamicCapability` autocmds may not run at all because buffer numbers may not be sequential numbers starting at 1. In such case, Goto Definition (`gd`), Rename (`<leader> cr`) and inlay hints are missing when jdtls is being loaded for the first time.
Getting `buffer` with `pairs` would fix the issue.
=> fix(lsp): properly get buffer for dynamic capabilities

lua/lazyvim/plugins/lsp/init.lua
Fixes #3309.
`LazyVim.config` gets evaluated during the parsing phase with `opts` as a table (thus not taking into account changes made in the user's personal configuration for the icons), so make `opts` a function to defer the evaluation until the plugin loads.
=> fix(lspconfig): make `opts` a function

lua/lazyvim/config/keymaps.lua, lua/lazyvim/plugins/editor.lua
I found that using Lazygit Commit Log is much more helpful. You can have all the Lazygit usefulness here.
I'm using it to browse the last commits, and then browse again the files that were changed in those commits, and using the `e` shortcut to open the file in the same Neovim instance.
=> feat(git): Change Commit Log to use Lazygit

lua/lazyvim/plugins/extras/lang/rust.lua
According to the maintainer of `rustaceanvim` (see his comment [here](https://github.com/LazyVim/LazyVim/pull/2198#issuecomment-1999475044)) he says
> To pick up on this: There's a good reason rustaceanvim doesn't automatically pick up a mason.nvim installation. It will most likely be built with a different toolchain than the one your project uses, often leading to discrepancies and subtle bugs.
It's easy to configure rustaceanvim to use mason.nvim if you really want it, but I generally adhere to the YAGNI principle.
I tried locally and the removal of `rust-analyzer` from `nvim-lspconfig` doesn't seem to have any effect on how `rustaceanvim` behaves.
I propose to remove all instances of `rust-analyzer` from `nvim-lspconfig` to avoid any possible issues from users that don't have …
=> fix(lang/rust): Remove `rust-analyzer` from `nvim-lspconfig`

lua/lazyvim/plugins/extras/util/gitui.lua
When using gitui, remove the gl keymap which is not remapped
=> fix: remove lazygit log gl keymap when on gitui

lua/lazyvim/plugins/extras/lang/typescript.lua
Based on [vtsls schema](https://github.com/yioneko/vtsls/blob/bd2df5a2d45cbc087e4fe285ec7c7396fd96e9cf/packages/service/configuration.schema.json#L1092), experimental setting should be vtsls property not typescript.
```json
"vtsls.experimental.completion.enableServerSideFuzzyMatch": {
"default": false,
"type": "boolean",
"description": "Execute fuzzy match of completion items on server side. Enable this will help filter out useless completion items from tsserver."
},
```
```lua
vtsls = {
enableMoveToFileCodeAction = true,
experimental = {
completion = {
enableServerSideFuzzyMatch = true,
},
},
},
```
=> Fix(extra: typescript): vtsls server experimental settings

lua/lazyvim/util/extras.lua
Similar to https://github.com/folke/lazy.nvim/commit/ea7b9c3c3fd9026e1a5ae27950585df9a42ccd5b# 
I only noticed this, because in my main config I have some Extras not managed by `LazyExtras`.
=> fix(extras): `underline = false` for setting diagnostics

lua/lazyvim/plugins/extras/lang/rust.lua
fix this warning
```
  Warn  11:52:45 PM notify.warn nvim-lspconfig.rust_analyzer has been setup.
This will likely lead to conflicts with the rustaceanvim LSP client.
See ':h rustaceanvim.mason'
```
fix taken from https://github.com/mrcjkb/rustaceanvim/blob/master/doc/mason.txt
=> fix(rust): let rustaceans.nvim setup rust_analyzer

lua/lazyvim/plugins/extras/lang/vue.lua
The existing Vue extra was not properly configuring vtsls to use the globalPlugin: `@vue/typescript-plugin`
This meant that even though the language server could load and provide hover info, it wouldn't provide any sort of autocomplete.
This commit fixes that by moving the `@vue/typescript-plugin` config to the vtsls settings and adding the line `configNamespace = "typescript"`. The fix does not work without the mentioned line.
I dont understand the intention behind LazyVim.extend() in the original code, given that the function takes two arguments and not three as provided. It also doesn't seem necessary to use any extend function to begin with either.
=> fix(extras.lang.vue) missing typescript autocomplete in .vue files

lua/lazyvim/plugins/extras/editor/outline.lua
=> fix(trouble): don't enable symbols keymap when `outline.nvim` enabled

lua/lazyvim/plugins/editor.lua
Using `toggle` with `Trouble todo` so that it can close Trouble with the same keybinding.
=> fix(todo-comments): use toggle for Trouble todo commands

lua/lazyvim/plugins/extras/editor/inc-rename.lua, lua/lazyvim/plugins/lsp/keymaps.lua, lua/lazyvim/plugins/ui.lua
Not sure how to safely move the LSP keymap into this file `<leader>cr`...
Using
`LazyVim.lsp.on_attach(function(client, buffer)`?
but how do I ensure that the function in the config for this extra gets called after the default lsp keymap one?
=> feat(editor-extra): Add inc-rename

lua/lazyvim/plugins/extras/lang/angular.lua
Since treesitter has better support for angular parser recently that works for the legacy and the latest version of it, I am happy to suggest this extra configuration that works for well for me without any issue. And since lack of references about how to config the angular lsp inside of neovim out there, this will work fine as a starting point.
=> feat(extras): Add extra for angular lspconfig

lua/lazyvim/util/toggle.lua
When closing Neovim with a window maximized toggled on, the session manager saves the value `999` for both `height/width`. So, next time Neovim starts it starts with a really weird layout because of that. I believe, since `toggle.maximize()` is intended as a toggle rather a permanent state, we should restore the `height/width` values to the ones before `maximize` was toggled on when quiting Neovim with a maximised window. 
Also, I'm most certain we don't want to use `QuitPre` event, but am unsure if we should choose `VimLeavePre` instead of `ExitPre`. Please make necessary changes according to what you think might be the best approach.
=> fix(toggle): Restore width/height values when closing while maximized is toggled on

lua/lazyvim/config/options.lua, lua/lazyvim/util/ui.lua
- Add to the status column the sign to indicate open fold, i.e where a fold will be triggered.
- Open and close fold sign will use the git sign color if it git info is present on the line (rel. line 5,4,2) and gitsigns' `signcolumn` is enabled (by default)
- otherwise close fold icon use "Folded" group, as before (line 7)
- open fold icon has no special highlight, the same as the number column (line 8, 3) 
This is similar to VSCode on mouse hover
=> feat(statuscol): fold open indicator

lua/lazyvim/plugins/extras/lang/python.lua
The regex branch belongs to the rewrite of the plugin. The changes brought in the new branch are quoted below.
<blockquote>
Why did you rewrite the plugin?
Because the current code has grown from supporting only simple venvs to lots of different venv managers. Each one works in a slightly different way, and the current code has lots of conditional logic to try and figure out what to do in certain situations. It made it difficult to change something without breaking something else. And it made it difficult to add features in a clean way.
This rewrite is about giving you as a user the power to add your own searches, and have anything you want show up in the telescope viewer. If its the path to a python executable, the plugin will attempt to activate it. Note that your LSP server must be …
=> Python Venv Selector: Switch to newer regexp branch

lua/lazyvim/plugins/extras/editor/mini-files.lua
* Makes the toggle_hidden keybinding configurable via mappings
* Adds new mini.files keybindings for opening files in a vertical split, with both go_in and go_in_plus modes (configurable via mappings)
* Adds new keybinding to change working directory from mini.files (configurable via mappings)
Closes #2692
=> feat(mini.files): add cwd and vertical/horizontal keybindings to mini.files

lua/lazyvim/plugins/extras/lang/angular.lua
Treesitter was not working in angular html templates after enabling `lang.angular` extra.
Added a change recommeded by angular treesitter developer to enable treesitter for components and containers.
[Reference to the recommendation for this hack](https://github.com/dlvandenberg/tree-sitter-angular?tab=readme-ov-file#filetype).
=> fix(extra.lang.angular): treesitter not enabled for angular templates

lua/lazyvim/plugins/extras/lang/angular.lua
This was previously attemped to be fixed by https://github.com/LazyVim/LazyVim/pull/3469, which caused an issue with angular LSP.
The PR was reverted as mentioned in https://github.com/LazyVim/LazyVim/pull/3485.
This PR implements suggestion by @folke, which fixes treesitter without breaking LSP.
=> fix(extra-lang-angular): re-fix angular html treesitter

lua/lazyvim/plugins/extras/lang/thrift.lua
This PR adds support for thriftls, the first line is because thrift is not among the neovim built-in file types.
=> feat(lang/thrift): add thrift lang support

lua/lazyvim/plugins/extras/lang/elm.lua
Adding https://elm-lang.org support.
- Adds `elm` Treesitter parsers
- Adds `elm-language-server` language server
- Adds `elm-format` formatter
The default [elm-language-server](https://github.com/elm-tooling/elm-language-server) configuration matches all [currently supported features for Neovim LSP](https://github.com/elm-tooling/elm-language-server#editor-support).
`elm-test` is not directly supported by [neo-test](../test/neotest) but it's available via [neotest-vim-test](https://github.com/nvim-neotest/neotest-vim-test).
However, it is common practice to peruse both [elm-test](https://github.com/elm-explorations/test/) and [elm-review](https://github.com/jfmengels/elm-review) directly via the command line.
=> feat(lang): add elm

lua/lazyvim/plugins/extras/dap/core.lua
Tested with `php` and `kotlin` Extras. 
`kotlin` Extra doesn't have the debug adapter in Mason `ensure_installed` and doesn't install automatically on its own. 
`php` Extra has the debug adapter defined in Mason `ensure_installed` and does correctly install automatically. However, this should not be needed due to `mason-nvim-dap`. If you remove [these lines](https://github.com/LazyVim/LazyVim/blob/ed93ce9c15cfe121b9cfb946b06b0449ae44486a/lua/lazyvim/plugins/extras/lang/php.lua#L26-L33), then the debug adapter doesn't automatically install, but it should.
With the change introduced in this PR, both Extras automatically install the debug adapters. `kotlin` Extra doesn't need anything else and in `php` Extra the lines I mentioned previously can be removed or not. The point is not to remove …
=> fix(mason-nvim-dap): correctly configure to auto-install debug adapters

lua/lazyvim/plugins/extras/lang/markdown.lua
missing `markdown-toc` in ensure installed for `extra/markdown`
=> fix(markdown): missing markdown-toc in mason

lua/lazyvim/plugins/editor.lua
I got this error message when opening telescope.
```
Failed to run `config` for telescope.nvim
...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:241: module 'trouble.sources.telescope' not found:
^Ino field package.preload['trouble.sources.telescope']
...
```
After investigating it, the reason was I have `trouble.nvim` disabled but the default base `opts` function is loading it.
I tried wrapping it with a function to lazy load the `trouble.nvim` module and it worked in my local setup.
=> fix(editor): telescope init error when trouble.nvim is disabled

lua/lazyvim/plugins/coding.lua
Make it easier, so if users decide to disable `nvim-snippets`, they don't have to remove the `snippets` source manually in their config.
=> fix(cmp): don't enable `snippets` source without `nvim-snippets`

lua/lazyvim/plugins/extras/lang/angular.lua
Sometimes angular treesitter didn't get started, e.g. when creating a new file.
- Add `BufNew` event to attach angular treesitter.
- Change `BufRead` to `BufReadPost` for better readability.
- [BufRead / BufReadPost docs](https://neovim.io/doc/user/autocmd.html#BufRead)
- [BufNew](https://neovim.io/doc/user/autocmd.html#BufNew)
=> fix(extra-lang-angular): add BufNew event to attach angular treesitter

lua/lazyvim/plugins/extras/dap/core.lua, lua/lazyvim/plugins/extras/lang/typescript.lua
`mason-nvim-dap.nvim` adds it's own adapter filetype mappings to the vscode extension in `nvim-dap` (as of https://github.com/jay-babu/mason-nvim-dap.nvim/pull/129)
This also moves the type mappings for the `pwa-node` and `node` adapters to where they are defined in the typescript pack.
Now that the default internal type mappings are configured we can rely on the automatic loading of the `.vscode/launch.json` that `nvim-dap` does
=> fix(typescript): clean up configuration of the vscode dap extension

doc/LazyVim.txt, lua/lazyvim/plugins/editor.lua
Similar to "trouble.nvim" I want the preview to open in the last active window. Currently the neo-tree preview opens in a floating window, which (to me) doesn’t look very good.
What do you think about doing preview window the same everywhere (trouble & neo-tree)?
https://github.com/LazyVim/LazyVim/assets/3313023/7d7c21c9-158d-40ef-82f2-62e0dc795555
https://github.com/LazyVim/LazyVim/assets/3313023/bafc5bae-20cb-4dd1-8e40-1358ada573d9
=> fix(neo-tree): use last window for preview

lua/lazyvim/util/lualine.lua
Adds a configurable lock icon when a file is opened as read only. Mimics `vi -R <file>` status line.
=> feat(lualine): show readonly icon

lua/lazyvim/plugins/extras/editor/mini-files.lua
Incorporate additional boolean logic when setting keymaps to avoid creating `opts.mappings` table and leave that only from the user configuration to change mappings.
=> refactor(mini-files): mini-files

lua/lazyvim/util/init.lua
This PR fixes a bug in the `LazyVim.memoize` function that was causing unexpected behavior in my configuration. The issue was discovered when setting `vim.g.lazyvim_prettier_needs_config = true` in my `lua/config/options.lua`, which did not work as expected.
The root cause was an issue with `LazyVim.memoize` cache key generation, which led to `M.has_config(ctx)` always returning the same result as `M.has_parser(ctx)`. This happened because `LazyVim.memoize` generates cache keys based on the function parameters, and both functions were being called with identical parameters:
https://github.com/LazyVim/LazyVim/blob/7d30360df29e0d02dd946521ff7fbfeea201b142/lua/lazyvim/plugins/extras/formatting/prettier.lua#L77-L81
By improving the cache key generation to include function information, we can …
=> fix(util): ensure unique cache keys in LazyVim.memoize

lua/lazyvim/plugins/extras/coding/copilot-chat.lua
Adds the abiltiy for fzf-lua to be used as a picker for these copilot chat actions if it was enabled in LazyExtras
This adds keybinds that exist currently for copilot-chat and Telescope but with the addition of fzf-lua as an extra, I noticed we needed the ability for the user to take advantage of them with FzfLua.
No
=> feat(copilot-chat): use fzf-lua if enabled in extras

lua/lazyvim/plugins/extras/ui/mini-indentscope.lua
If `fzf-lua` and `mini.indentscope` are enabled together, the indent line created by `indentscope` makes the fzf window hard and confusing to work with
PS: also sorted the file list.
I don't think there's an existing issue for this.
=> fix(fzf): disable mini.indentscope in fzf-lua buffer

lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/extras/editor/telescope.lua
`have_make` and `have_cmake` were left over at `/lua/plugins/editor.lua`, so move them to `extras.editor.telescope` instead.
No
=> fix(pick): move some leftovers from `editor.lua` to `editor.telescope`

lua/lazyvim/plugins/extras/editor/fzf.lua
- floating previewer closed fail. https://github.com/LazyVim/LazyVim/issues/3582
=> fix(fzf): floating previewer closed fail

.github/ISSUE_TEMPLATE/bug_report.yml
repro.lua didn't work. at least i don't think it's the intended behaviour.
it installed lazy.vim, lazy.nvim, tokyonight.
but didn't actually load lazyvim, and so none of it's plugins config etc...
=> fix(issue template): repro.lua didn't work

lua/lazyvim/plugins/extras/lang/vue.lua
can not inc-rename when volar is enabled.
After the configuration in commit was added, the inc-rename operation returned to normal.
I suspect that volar's Hybrid mode affects the rename operation.
https://github.com/vuejs/language-tools?tab=readme-ov-file#none-hybrid-modesimilar-to-takeover-mode-configuration-requires-vuelanguage-server-version-207
=> fix(vue): can not inc-rename

lua/lazyvim/plugins/extras/lang/rust.lua
After recent changes in `rustaceanvim` in https://github.com/mrcjkb/rustaceanvim/pull/403, `checkOnSave` is supposed to be boolean and the table that we were passing to `checkOnSave` previously should be passed to `check` instead. I left the `check` table undefined, because the options that we were passing to `checkOnSave` before are the default ones being passed to `check`. So, only if the user wants to change something should he change the values of the `check` table according to what he wants.
No
=> fix(lang): incorporate latest changes from `rustaceanvim`

lua/lazyvim/plugins/extras/lang/elixir.lua
add missing elixir lspconfig
lspconfig is missing for elixir and since mason was removed in https://github.com/LazyVim/LazyVim/commit/f8268faa7c705cca7047fbaef5984905b47a7324, elixirls is no longer automatically installed.
=> fix(elixir): add missing lspconfig

lua/lazyvim/plugins/extras/ui/edgy.lua
When the user disables a specific neo-tree source (git_status or buffers), the panes are still created but throw an error when the user tries to open them
**NB**: This is currently not functional because `LazyVim.opts` is returning an empty table instead of the neo-tree opts. I'm hoping someone can give me a hand with this little problem
=> fix(egdy): do not add panes for not enabled neo-tree sources

lua/lazyvim/util/pick.lua
When we register a picker, such as a Telescope picker or a fzf-lua picker, 
we use commands within their own picker. For example, we use M.picker.commands instead of M.pick.commands.
no
=> fix(pick): remove the unused commands attribute

lua/lazyvim/util/init.lua
Small refactor to use the already available `get_plugin()` function.
No.
=> refactor(util): use available get_plugin() function

lua/lazyvim/plugins/extras/lang/php.lua
- Allows setting intelephense instead of phpactor for PHP's LSP
No. But I personally use intelephesen myself and when researching on how to use the PHP extras but swap phpactor (too verbose, imo) for intelephense, I found this [comment here](https://github.com/LazyVim/LazyVim/pull/3397#issuecomment-2141950186) which suggested making it configurable like the Python extras. That's what I'm doing here.
=> feat(extras): allow using intelephense instead of phpactor in php extras

lua/lazyvim/plugins/formatting.lua
`conform.nvim` had breaking changes, that renamed `lsp_fallback` to `lsp_format` as can be seen [here](https://github.com/stevearc/conform.nvim/commit/9228b2ff4efd58b6e081defec643bf887ebadff6)
Fixes #3706
=> fix(conform): `lsp_format` breaking changes

lua/lazyvim/plugins/coding.lua
Fix nvim-snippets' <S-Tab> rollback keymap.
=> fix(snippets): nvim-snippets `<S-Tab>` prev key

lua/lazyvim/util/ui.lua
Fix correctly showing relative numbers in `statuscolumn` after recent breaking changes on [nightly](https://github.com/neovim/neovim/pull/29357).
Please feel free to disregard this PR if a better solution is possible.
Fixes #3721
=> fix(statuscolumn): `%r` deprecated in nightly and `%l` handles everything

lua/lazyvim/plugins/extras/lang/python.lua
On Windows, when using dap, python.exe will launch an extra console. If you target pythonw.exe this avoids that. Explanation source: https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe
Modify which exe is targeted for python + dap on windows. If you use python.exe an extra console launches (eg, nvim is runnining on Wezterm, boot up dap, and as a result an external console (usually through windows terminal or built-in console terminal) will launch (dap still runs in the original window). This is avoided with pythonw.exe
No
=> fix(extras.python): avoid launching extra console with dap on Windows

lua/lazyvim/config/autocmds.lua, lua/lazyvim/plugins/editor.lua
Also add filetype `gitsigns.blame` to autocmd `lazyvim_close_with_q` and workaround for `+hunks` group name to show prefix correctly. If you don't like the workaround for `+hunks` group name feel free to remove it.
Make use of the new `gitsigns` feature `Gitsigns blame`, which shows in a vertical buffer split the `blame` history of the whole buffer.
No.
=> feat(gitsigns): new keymap for `Gitsigns blame`

lua/lazyvim/util/ui.lua
After some recent changes in https://github.com/neovim/neovim/pull/28709 I was getting an error when the user had `folds_open = true` in his personal configuration whenever he pressed `o/O`. This is an attempt to fix that.
I was getting an error with `folds_open = true` in the user configuration whenever pressing `o/O` or pressing `Enter` for a new line.
The error was `Error executing lua: ...e/jrn23/projects/plugins/LazyVim/lua/lazyvim/util/ui.lua:127: attempt to index a number value`.
No
=> fix(statuscolumn): fix `folds_open = true`

lua/lazyvim/plugins/extras/lang/go.lua, lua/lazyvim/plugins/extras/test/core.lua
This PR switches [nvim-neotest/neotest-go](https://github.com/nvim-neotest/neotest-go) for [fredrikaverpil/neotest-golang](https://github.com/fredrikaverpil/neotest-golang).
Neotest-go comes with some problems which are mitigated in neotest-golang. A full description/background is available in the project README, but here are some highlights:
- Test Output in JSON, making it difficult to read:  [neotest-go#52](https://github.com/nvim-neotest/neotest-go/issues/52)
- "Run nearest" runs all tests:  [neotest-go#83](https://github.com/nvim-neotest/neotest-go/issues/83)
- Running test suite doesn't work:  [neotest-go#89](https://github.com/nvim-neotest/neotest-go/issues/89)
- Diagnostics for table tests on the line of failure:  [neotest-go#75](https://github.com/nvim-neotest/neotest-go/issues/75 …
=> feat(go): switch to neotest-golang

lua/lazyvim/plugins/extras/ui/edgy.lua
Refactor neo-tree related logic
Simplification of `neo-tree` related logic in `edgy.lua`
No, but it may prevent future issues with `edgy` if `neo-tree` source configuration changes.
=> refactor(extras.ui): simplify neo-tree related logic in edgy extra

lua/lazyvim/plugins/editor.lua
I'm used to jumping from git hunks with `[h` so I'd like to use the same mapping when navigating diffs.
No
=> feat(gitsigns): navigate diff changes as well as git hunks with [h/]h

lua/lazyvim/plugins/extras/dap/core.lua
Only `require("mason-nvim-dap")` when it's not disabled
Fixes #3783
=> fix(dap): only load `mason-nvim-dap` when not disabled

lua/lazyvim/plugins/extras/lang/astro.lua
Support [`astro.config.ts`](https://docs.astro.build/en/guides/configuring-astro/#supported-config-file-types) as a root file for the Astro extra.
N/A
=> fix(extras.astro): support `astro.config.ts` root

lua/lazyvim/plugins/extras/editor/fzf.lua
Disable `preview` in `fzf-lua` Extra for `vtsls`. I tested it with Python and Typescript Extras and in Typescript pressing `<leader>ca` shows without previewer, while in Python the same shows with previewer. 
Kindly check also that this is correct and I didn't miss out anything else.
Fixes #3773
=> fix(fzf): disable `preview` for `vtsls`

lua/lazyvim/plugins/extras/lang/elixir.lua
Fix detection of elixir `credo` linter. 
`vim.fn.executable("credo") == 0` will never succeed because `credo` is not binary/executable. It is a `mix` package and only available via `mix credo` command.
Instead, the plugins(both `none-ls` and `nvim-lint`) will check for the presence of the `.credo.exs` file.
Fixes #3808
=> fix(elixir): fix credo detection for elixir linters.

lua/lazyvim/plugins/extras/lang/sql.lua
A small contribution to enhance the documentation and make it easier to use.
While vim-dadbod and vim-dadbod-ui recommend using dotenv.vim for env file injection, we aim to provide a simpler method. Instead of implementing file parsing or relying on an external plugin (dotenv.vim), just try directly using a Lua table.
none!
=> feat(extra.sql): add sql options docs

lua/lazyvim/plugins/extras/test/core.lua
Similar to https://github.com/LazyVim/LazyVim/issues/847 , only this adapter adds a setup function into the 'adapter' key in the plugin table ([source](https://github.com/thenbe/neotest-playwright/blob/f61463f5c74d53fc5975b7e086b7c6e9356d9215/lua/neotest-playwright/init.lua#L31-L33)).
It is somewhat annoying that neotest does not provide a recommended way for adapters to define their configuration function (at least not explicitly)...
Perhaps we should work around it temporarily, but reach out to either neotest or neotest-playwright authors?
I didn't see anyone complaining about playwright adapter in issues or discussions :/
=> fix(neotest): support adapter key on adapter for playwright

lua/lazyvim/plugins/linting.lua
There's some logic in `linting.lua` to allow for easy setting of linter args, but it doesn't work when default args is empty. This hopefully fixes it.
N/A.
=> fix(lint): make prepend_args opt work when default args is empty

lua/lazyvim/plugins/editor.lua
Fixing inconsistency with the `gitsigns` signs.
Since the signs are overridden ...
https://github.com/LazyVim/LazyVim/blob/5e1c474192372caca7d95d4a85dd5939fe95cca3/lua/lazyvim/plugins/editor.lua#L201-L209
The staged signs should be overridden too.
> ```
> signs_staged                                    *gitsigns-config-signs_staged*
>       Type: `table[extended]`
>       Default: >
>         {
>           add          = { text = '┃' },
>           change       = { text = '┃' },
>           delete       = { text = '▁' },
>           topdelete    = { text = '▔' },
>           changedelete = { text = '~' },
>         }
> <
>     Configuration for signs of staged hunks.
> 
>     See |gitsigns-config-signs|.
> ```
https://github.com/lewis6991/gitsigns.nvim/blob/0595724fa9516a35696ff6b1e3cb95b6 …
=> fix(gitsigns): fix inconsistent signs

lua/lazyvim/util/ui.lua
When you hit `Cancel` and a buffer is modified, it should not delete the buffer.
Fixes #3832
=> fix(bufremove): fix `Cancel`

lua/lazyvim/plugins/extras/lang/markdown.lua
This PR switches makrdownlint-cli to markdownlint-cli2.
markdownlint-cli2 should be a bit faster than markdownlint-cli and has a more flexible configuration through files in the whole directory tree.
The cli is maintained by David Anson who also wrote the markdown style checker itself which is used by the "old" cli and cli2.
Blog post from David Anson regarding the new cli itself:
https://dlaa.me/blog/post/markdownlintcli2
No
=> feat(extras): switch to markdownlint-cli2

lua/lazyvim/util/lazygit.lua
Current implementation of `Git Browse` doesn't work with onprem gitlab (and any other git hosting except gitlab, github and  bitbucket).
With this little fix, it should work with any git hosting.
No
=> fix(lazygit): fix browsing private git hostings

lua/lazyvim/plugins/extras/ui/edgy.lua
Use already defined Bufferline offsets or use Edgy offset if none are found.
Also properly set offset separator position depending on offset/pane location.
No
=> fix(edgy): improve edgy.lua bufferline offset logic

lua/lazyvim/plugins/extras/lang/java.lua
jdtls needs an argument passed to the JVM to load Lombok as an agent.
Mason downloads `lombok.jar`so we can use that
Configures Lombok support in `jdtls` ; this removes a lot of red underlines in Java projects that use it.
Changes this
To this
=> feat(java): enable Lombok support in jdtls

lua/lazyvim/plugins/coding.lua
Tries to improve aesthetics for `nvim-cmp` in Rust by disabling `item.menu` since it contains the `return` types that take up too much space.
Fixes #3855
=> feat(cmp): disable `item.menu` for Rust filetypes

lua/lazyvim/plugins/editor.lua
`branch` was obstructing from being able to update to latest HEAD like in other plugins. This was necessary when the initial development was being done on this branch and `main` was used for the old stable release, but this is not necessary any more. Also, @folke now you can use `always_show_by_pattern`, which you might find useful to show the git tracked hidden files like you wanted but couldn't do before. 
No
=> fix(neo-tree): remove `branch`, since it obstructs updating to latest version

lua/lazyvim/plugins/coding.lua
Attempt for dynamic width and trimming between fields.
Testing was done on my 15.6 laptop screen so maybe values could be raised in dynamic calculation? Also provides a `vim.g.cmp_fixed_width` for the users to be able to define a fixed width in their personal configuration if they'd like to.
Attempts to rectify a concern raised in #3858
=> feat(cmp): attempt for dynamic width and trimming between fields

lua/lazyvim/plugins/extras/util/chezmoi.lua
This fixes an issue with the chezmoi extra that won't work if the LazyVim picker is fzf-lua instead of Telescope. Fx if you have the `editor.fzf` and `util.chezmoi` extras enabled at the same time, trying to open the config from the dashboard will result in the following error because Telescope has been replaced with fzf:
```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:E492: Not an editor command: Telescope chezmoi find_files
stack traceback:
[C]: in function 'nvim_exec2'
vim/_editor.lua: in function 'cmd'
...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:24: in function <...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:20>
```
This PR fixes the issue by checking which LazyVim picker is in use. 
Before: …
=> fix(chezmoi): missing support for fzf file picker

lua/lazyvim/plugins/extras/editor/fzf.lua
It seems that the preview keymaps set right now only support the builtin previewer. 
From searching through `fzf-lua` docs, I found [here](https://github.com/ibhagwan/fzf-lua/blob/3b91c1a471160bd8620bdca8f18743d954994daa/README.md?plain=1#L634-L638) that additional mappings should be set for the other previewers such as `git` (otherwise the defaults `<shift-down/up>` could be used).
I chose to use the same mappings for the `fzf` preview keymaps as they serve the same functionality. Please feel free to change if not to your liking.
Not an issue but a discussion #3895
=> feat(fzf-lua): preview keymaps for git

lua/lazyvim/plugins/ui.lua, lua/lazyvim/util/mini.lua
Replace the icon support with the new mini library
=> feat(ui): use `mini.icons` instead of `nvim-wev-devicons`

lua/lazyvim/plugins/editor.lua
A user won't also have to override the keymaps if they set options for `Trouble lsp` or `symbols` in `opts` (assuming they want the mode to always open with certain options).
No.
- [ x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.
----
The default for `Trouble symbols` already seems to be on the right, and neither lsp/symbols auto-focuses, so I left these out.
=> refactor(trouble): move options in keymaps for lsp and symbols to `opts`

lua/lazyvim/plugins/extras/util/project.lua
In project extra, when using `<c-w>` in the project selection menu to change directory, the window used to show the command's exit code would not close. This fixes it.
N/A.
=> fix(project): properly close window after changing directory

lua/lazyvim/plugins/extras/editor/dial.lua
Move augends `ordinal_numbers`, `weekdays` and `months` to the default group, making them available to all filetypes. I don't think there is a concrete reason to restrict them to specific filetypes.
N/A.
=> fix(dial): move date related augends to default group

lua/lazyvim/plugins/extras/editor/outline.lua
The symbols-outline extra was removed in favor of outline.nvim in #2535 (thanks!), but the configuration for symbols in outline.nvim [is not backwards-compatible](https://github.com/hedyhli/outline.nvim/issues/12).
This fixes the configuration for the symbols icons and filter to be usable by outline.nvim.
It doesn't seem like anyone has encountered this issue, but I can confirm that the config currently used by LazyVim is incorrect. The symbols table is at `symbols` for symbols-outline.nvim, but it's now at `symbols.icons` for outline.nvim.
There is no such `symbols_blacklist` key. Instead, `symbols.filter` is used, which is a kind of "whitelist".
Coincidentally, outline.nvim fully supports the LazyVim `kind_filter` config table structure. It can either be a list of strings (kinds), or a …
=> fix(outline): use the correct symbols and filter config format

lua/lazyvim/config/options.lua, lua/lazyvim/plugins/extras/lang/vue.lua
At the moment, the config for vue set hybrid mode to `false` which volar will run a typescript server under the hook. ( hybrid mode false is the takeover mode in v1, was introduced in `2.0.7` see more information here: https://github.com/vuejs/language-tools/pull/4119 ).
However, another vtsls with vue language plugin also attached to vue files, this will cause two typescript server running at the same time. It can be very easily observed with tools like `htop` volar and vtsls will have similar memory usage which is abnormal because volar should be very light by itself. This will introduce issues like duplicate diagnostics, see  https://github.com/vuejs/language-tools/issues/4159#issuecomment-2208101079
In this pull request, I set the hybrid mode to true as default because the hybrid mode …
=> feat(vue): enabled hybrid mode to avoid 2 typescript lsp running at same time

lua/lazyvim/plugins/ui.lua
`mini.starter` recently had a breaking change to set the file type to `ministarter` instead of the old `starter`; so, `lualine` is enabled in the dashboard because it's using the old file type.
No.
=> fix(lualine): use the new ministarter file type to disable in mini.starter

lua/lazyvim/plugins/extras/ui/mini-starter.lua
In a fresh install of lazyvim (with` neovim nightly or stable), the startup time is not shown in the mini.starter extra. This fixes it.
The filetype name has changed in mini.starter
https://github.com/echasnovski/mini.starter/commit/394994b2bec10a997c69575825d5c444957b9ff9
Did not find an issue for it.
=> fix(mini.starter): lazyvim startuptime in mini.starter

lua/lazyvim/plugins/extras/lang/java.lua
Allow overriding java test config
NO
=> feat(java): allow overriding test config

lua/lazyvim/plugins/extras/lang/java.lua
Problem
In the default configuration `opts.test` is a boolean and the code tries to access `opts.test.config_overrides` which results in an error.
Solution
Use control flow to return nil in the case of `opts.test` being boolean.
- Fixes #3965.
- [ x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.
=> fix(java): fix `config_overrides` for tests

lua/lazyvim/plugins/extras/lang/php.lua
`conform.nvim` was not using the correct formatter name for `php-cs-fixer` (which is the name of the binary). 
Also move `conform.nvim` spec outside of `nvim-lint` spec.
Fixes #3985
=> fix(php): `php_cs_fixer` is the correct name

lua/lazyvim/plugins/extras/editor/outline.lua
In `outline.nvim` we have `symbols.filter = LazyVim.config.kind_filter`. `outline.nvim` adds an entry `exclude = false` by default when it's a table. This entry propagates to `LazyVim.config.kind_filter` and when using `LazyVim.config.get_kind_filter()` in Telescope `<leader>ss` that entry is there as well and causes the error in https://github.com/nvim-telescope/telescope.nvim/blob/bfcc7d5c6f12209139f175e6123a7b7de6d9c18a/lua/telescope/utils.lua#L143. Use `vim.deepcopy` to create a new object for `symbols.filter` in `outline.nvim`, so that the additional entries don't propagate to default `LazyVim.config.kind_filter`.
Fixes #4003
=> fix(outline): use new object for `symbols.filter`

lua/lazyvim/plugins/extras/editor/leap.lua
The flit config overrides the descriptions provided by the which-key presets plugin for the `f`/`F`/`t`/`T` motions with an unhelpful description text (just the key itself).
Remove the `desc` argument so that which-key uses the existing description (e.g "Move before next char").
| Before | After |
| ------------- | ------------- |
| ![Before](https://github.com/user-attachments/assets/39b885fe-95c2-4a6e-8b22-4e5ddf1986a9) | ![After](https://github.com/user-attachments/assets/6042fde3-e135-48fa-b1fd-c6047277903a)  |
=> fix(flit): use which-key preset keymap descriptions

lua/lazyvim/plugins/extras/lang/java.lua
Use which-key v3 format for java mappings.
`<leader>c` is removed as it is reported as a duplicate mapping in health check.
=> feat(java): new java mappings format for which-key v3

lua/lazyvim/plugins/extras/lang/omnisharp.lua
Debugging c# with the Omnisharp plugin doesn't work, as described by myself in #4004. Turns out this is a known issue with how nvim-dap calls the mason netcoredbg cmd script. [The solution](https://github.com/jay-babu/mason-nvim-dap.nvim/issues/132) is to pass `detach = false` as an option to the debug adapter. I've tested and it works on my windows machine.
#4004
=> fix(omnisharp): don't detach coreclr debug adapter

lua/lazyvim/plugins/extras/lang/tailwind.lua
Tailwind completions stopped working in Phoenix projects that have `HTML`, `HEEX` or `Elixir files with ~H sigils`. 
Broader discussion and recommended solution: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1002
=> fix(tailwind): additional tailwind completion settings for phoenix projects

lua/lazyvim/plugins/extras/coding/luasnip.lua
this makes the extra luasnip lazy load at the same time as nvim cmp.
just putting `lazy = true` works because `nvim-cmp` when being loaded with `InsertEnter` also load `cmp-luasnip`, which itself load `LUASNIP`.
you can see the problem in the following discussion https://github.com/LazyVim/LazyVim/discussions/3966 where luasnip was not lazy loaded when starting lazyvim. This was also loading nvim-cmp and all its dep when starting lazyvim, which negatively impacted performance.
https://github.com/LazyVim/LazyVim/discussions/3966
=> fix(extra): luasnip wasn't lazyloaded

lua/lazyvim/plugins/extras/lang/r.lua
A new feature was added to `r.nvim` that added a new key bind. This pr adds that key bind (and group in case more are added) to the current which-key config.
(I also removed a comment that I made previously for increasing the width of the which-key window to fit the longer keybind descriptions, something that eventually was taken out of the previous PR long ago)
None
=> feat(R): added new which-key group for new install feature

lua/lazyvim/util/terminal.lua
Often times when opening a terminal or lazygit when a search is active, words in the terminal are highlighted. In my opinion this is rarely, if not never intended. This attempts to fixes this behavior. The code of `terminal.lua` is a bit beyond me, but I believe I have added it to the right place.
N/A.
=> feat(terminal): clear search highlight when opening a terminal

lua/lazyvim/plugins/ui.lua
Right now there is a default `vim.g.trouble_lualine` being set to `true`, and only that variable is being checked when deciding if the trouble output is being appended to the `lualine_c` for the lualine plugin. This is normally nice in code files, where you can get output like `packages/src/index.ts > myFunction` but in some filetypes, the user may not wish for this. In particular, I found if you have files with the `markdown` type that include long headers, then you can easily lose the file name by it trying to include the headers in this location.
Considering that one of the `CONTRIBUTING.md` guidelines is `Ensure all configurations are overridable by the user, using Lazy's specs.`, I figured that allowing this to be overrideable at the user's discretion could be a valuable feature. …
=> feat(lualine): allow for trouble_lualine to be overriden on buffer

lua/lazyvim/plugins/extras/lang/ruby.lua
Shopify started working on its own LSP (https://github.com/Shopify/ruby-lsp) and it performs way better than Solargraph which has a lot of limitations. This paired with sorbet gives better IntelliSense when navigating the code.
This PR follows the same approach as Python and lets the user configure through vim.g options the lsp and formatter for ruby, without overriding any configuration.
One caveat though is that RubyLsp does not work very well with NeoVim < 0.10 https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#neovim
=> feat(extras): improve ruby extra by letting user chose

lua/lazyvim/config/init.lua
See [this](https://github.com/LazyVim/LazyVim/discussions/4112) discussion
TLDR: 
Startup time performance is affected quite significantly when the clipboard provider is `xsel`(linux) or `pbcopy`(macos). I expect an improvement in these cases, especially on older pc's.
This PR resets `vim.opt.clipboard` after the `options` are loaded. Then, on `VeryLazy`, the setting is restored.
I also tested with `yanky`.
Relevant prints:
1. Before resetting `vim.opt.clipboard` in `init`, `vim.print(vim.opt.clipboard)` yields a table which will be captured:
```lua
--- fields
_name = "clipboard",
_value = "unnamedplus",
--- more fields
```
2. Set `vim.opt.clipboard = ""` and `vim.print(vim.opt.clipboard)`, also yields a table:
```lua
--- fields
_name = "clipboard",
_value = "",
--- more fields
```
=> feat(core): defer clipboard because xsel and pbcopy can be slow

NEWS.md, lua/lazyvim/config/autocmds.lua, lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/extras/ui/mini-animate.lua
I'm considering to replace [nvim-spectre](https://github.com/nvim-pack/nvim-spectre) with [grug-far.nvim](https://github.com/MagicDuck/grug-far.nvim).
It has a better ui and I like the workflow better.
I won't merge this right away. I'm mostly looking for feedback on whether this would be a good thing and whether the defaults option I've added seem ok.
=> feat(editor): replace nvim-spectre with grug-far.nvim

lua/lazyvim/plugins/ui.lua
Add which-key toggle mappings for toggling both the indention guides, and also scope highlight on a per buffer basis.
=> feat(indent-blankline): add which-key toggles

lua/lazyvim/plugins/extras/lang/python.lua, lua/lazyvim/plugins/lsp/init.lua
Change default python ruff lsp from `ruff_lsp` to `ruff`. It is now marked as stable. I have been using it for a few days without any problems. I use python for relatively small to medium projects. Maybe someone who is using python more rigorously has better feedback.
References:
https://github.com/astral-sh/ruff-lsp (see note)
https://github.com/astral-sh/ruff/releases/tag/0.5.3
https://docs.astral.sh/ruff/editors/setup/#neovim
Also the issue in https://github.com/LazyVim/LazyVim/pull/3057 has been resolved. I tested it and I only get 1 `ruff server` process per nvim instance. The processes close correctly when nvim is closed.
=> feat(python): default to new ruff instead of ruff_lsp

lua/lazyvim/plugins/extras/lang/elixir.lua
This is a refactoring of #3846  with the changes:
- Use `Lazyvim.lsp.execute` on keymaps to make everything simpler;
- Remove expandMacro. 
Closes #3846
=> feat(elixir): add elixirls code actions

lua/lazyvim/plugins/colorscheme.lua
This enables the recently added `grug-far` integration in catppuccin - https://github.com/catppuccin/nvim/pull/735
=> feat(catppuccin): enable grug-far integration

lua/lazyvim/plugins/extras/lang/markdown.lua, lua/lazyvim/util/plugin.lua
As described in https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/aeb5cec617c3bd5738ab82ba2c3f9ccdc27656c2
=> chore(markdown): markdown.nvim was renamed to render-markdown.nvim

lua/lazyvim/config/options.lua, lua/lazyvim/util/lazygit.lua
This takes into consideration an additional file, if it exists, to extend `LG_CONFIG_FILE` environment variable, so that users can overwrite easier default LazyVim options set for lazygit in `lazygit-theme.yml`. It's not desirable to directly change `lazygit-theme.yml` as the values are hardcoded and regenerated upon colorscheme change.
Fixes #4364. Ideally, the problem about `nvim-remote` on Windows should be fixed on lazygit's side, so this is just kind of a hotfix in the meantime. Feel free to disregard this if not desirable.
=> feat(lazygit): allow user to override LazyVim config with custom file

lua/lazyvim/plugins/extras/lang/markdown.lua
This fixes the problem when checking for updates and trying to build and the user encounters the error `unknown function mkdp#util#install`. 
As per https://github.com/iamcco/markdown-preview.nvim/pull/691
No, rather a discussion #4194
=> fix(markdown-preview): unknown function `mkdp#util#install`

lua/lazyvim/util/toggle.lua
This makes `toggle.diagnostics` compatible with Neovim 0.9.5 (though not sure about the metatable callables, since `set` there accepts a boolean from `get` state). 
Please make whatever changes you deem necessary or disregard as a whole for a better approach I haven't been able to think of.
Fixes #4203
=> fix(toggle): make `diagnostics` compatible with nvim-0.9.5

lua/lazyvim/plugins/extras/coding/copilot-chat.lua
CopilotChat upgraded to gpt-4o early in August https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/2c4d2954f9b56945dc8d053903b16759d08f9f37 but the LazyVim plugin is still running with opts of gpt-4. I thought about changing model to the latest here, but I feel this means more maintainability for an option which generally is expected to point to the latest model, and the upstream opts of CopilotChat seem to keep up with that already.
None
None
=> fix(extra): make copilot-chat.lua fallback to the latest model

lua/lazyvim/plugins/editor.lua
Just a very simple fix to use the updated method in grug to set the options for the dependency. Just ran across the issue debuging search and replace on my setup (was not the issue). 
This is not breaking.  
N/A
N/A
=> fix(grug): grug_far -> grug.open

lua/lazyvim/plugins/extras/lang/ocaml.lua
This fixes the error users get from local function `get_language_id`. 
From looking into [nvim-lspconfig ocamllsp](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/ocamllsp.lua) and other googling around, namely [tjdevries config files](https://github.com/tjdevries/config.nvim/blob/9b790b90c1ac68cf7e60d6537baf9395523d6b01/lua/custom/plugins/lsp.lua#L108-L115) and [another one](https://github.com/nyinyithann/neovim-ocaml/blob/e31c0d61fd78a2d367bacfae2886629a2c7a88d7/nvim/after/plugin/lspconfig.lua#L67), it seems that we can directly set these as filetypes foregoing the mapping via the additional local function which would also need the [nvim-lspconfig language_id mapping](https://github.com/neovim/nvim-lspconfig/blob/d4814330b207a4e05ba9515e453b0e87f2 …
=> fix(ocaml): get_language_id

lua/lazyvim/plugins/extras/lang/astro.lua, lua/lazyvim/plugins/extras/lang/vue.lua
If css treesitter is not installed(the current), <style> in vue file will use wrong commentstring, ts-comments.nvim or nvim-ts-context-commentstring both. so ensure it's installed.
explained: [in https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/117](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/117#issuecomment-2287909324)
close https://github.com/LazyVim/LazyVim/issues/4292
=> fix(vue): ensure css treesitter installed

lua/lazyvim/plugins/extras/lang/omnisharp.lua
There was a problem with Omnisharp with fzf.lua enabled instead of telescope. As discussed in #4258, this change makes Go To Definition work with fzf.lua.
- Fixes #4258 
- [x ] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.
=> fix(omnisharp): use Go To Definition with fzf.lua

lua/lazyvim/plugins/extras/lang/java.lua, lua/lazyvim/plugins/extras/lang/lean.lua, lua/lazyvim/plugins/extras/lang/tailwind.lua
https://github.com/neovim/nvim-lspconfig/commit/bedb2a0df105f68a624a49b867f269b6d55a2c89 introduces a change to the Lua module structure for `nvim-lspconfig` that broke `tailwindcss`.  Tried to also address all the other usages of `lspconfig.server_configurations` within the ecosystem.
=> fix(extras): rename `lspconfig.server_configurations` to `lspconfig.configs`

lua/lazyvim/plugins/extras/lang/markdown.lua
After https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/cb9a5e2412d21c7a89627e0d6da5459acbc0eb9c there's no need for defining filetypes both in Lazy's `ft` and the plugin's `opts.file_types`.
None
=> fix(render-markdown): remove redundant `opts.file_types`

lua/lazyvim/plugins/extras/lang/typescript.lua
In this [PR](https://github.com/neovim/nvim-lspconfig/pull/3232), tsserver is renamed to ts_ls, but it hasn't been released yet. 
Therefore, ts_ls is added to the LSP configuration in case the user updates their plugins locally.
N/A!
N/A!
=> feat(lang): add ts_ls to lsp config

lua/lazyvim/util/toggle.lua
Add to `M.wk` fields for `icon`, `color_enabled` and `color_disabled` for more granual user customization.
No, rather a discussion #4512
=> feat(toggle): add more `M.wk` fields for better user customization

lua/lazyvim/plugins/extras/lang/rust.lua
The recommended version of rustaceanvim has changed to 5.x, which brings in a lot of improvements.
Version 5.x of rustaceanvim has a lot of improvements over 4.x, and is the recommended version according to its maintainer.
=> feat(rust): update rustaceanvim

lua/lazyvim/config/autocmds.lua
There was a change in `gitsigns` filetype name for blame.
No
=> fix(gitsigns): change name of filetype blame

lua/lazyvim/config/keymaps.lua
Allow user to use `v:count1` when moving lines
Closes #4615.
=> feat(keymaps): allow `v:count1` when moving lines

lua/lazyvim/plugins/coding.lua, lua/lazyvim/plugins/extras/coding/tabnine.lua, lua/lazyvim/plugins/extras/lang/python.lua, lua/lazyvim/plugins/extras/lang/rust.lua, lua/lazyvim/plugins/extras/lang/tailwind.lua
Makes it easier to disable it for users who want to try other completion engines, without it being pulled back by some Extra.
None
=> refactor(cmp): add `optional` where necessary

lua/lazyvim/plugins/extras/dap/core.lua
The explicit call to `load_launchjs` is unnecessary, since after https://github.com/mfussenegger/nvim-dap/pull/1237 `.vscode/launch.json` files are loaded automatically.
Fixes #4432
=> fix(dap): remove explicit `load_launchjs` call

lua/lazyvim/config/autocmds.lua
Currently `checkhealth` buffers stay visible on `bufferline` when you close them with `q`. Use `:bd` instead to delete the buffer from bufferlist. `vim.schedule` is needed because `LspInfo` adds its own mapping to close the window (see [here](https://github.com/neovim/nvim-lspconfig/blob/edd9591199d1c78c0cb20514231f7f936f9412a2/lua/lspconfig/health.lua#L328)), so we need to overwrite it.
None
=> fix(autocmds): change mapping for `lazyvim_close_with_q`

lua/lazyvim/config/keymaps.lua
When using `<leader>gf` Lazygit is launched in the current directory rather than the root directory.
=> fix(lazygit): file history when cwd is outside the repo

lua/lazyvim/plugins/extras/lang/rust.lua
Rather than manually handling hover and completions through nvim-cmp and nvim-lspconfig, enable the crates.nvim in-process lsp server. This also allows crates.nvim to provide code actions.
This change also removes the direct dependency on nvim-cmp, which should help with #4680
=> feat(extras): enable crates.nvim in-process lsp server

lua/lazyvim/plugins/extras/coding/copilot-chat.lua
Check for cmp before setting up copilot chat.
For https://github.com/LazyVim/LazyVim/issues/4702
I would like to set up the cmp compatability later if possible, but this is a quick patch to allow copilot chat to work without cmp (for now).
=> fix(copilot-chat): setup cmp conditionally

lua/lazyvim/plugins/extras/formatting/prettier.lua
This change makes it possible to configure other formatters for filetypes supported by the prettier extra, for instance
```js
return {
{
"stevearc/conform.nvim",
opts = {
formatters_by_ft = {
css = { "stylelint" },
},
},
},
}
```
Currently the prettier extra overwrites any existing `formatters_by_ft` for the filetypes it supports. I've changed it to use `table.insert` [like the sql extra does](https://github.com/LazyVim/LazyVim/blob/75750be1c0493659c9fbc60ff5e06dba053ef528/lua/lazyvim/plugins/extras/lang/sql.lua#L148-L149).
None that I know of
N/A
=> fix(prettier): keep existing formatters_by_ft

lua/lazyvim/plugins/extras/lang/nushell.lua
Since the nushell treesitter parser is now upstream, as seen in [this pr](https://github.com/nvim-treesitter/nvim-treesitter/pull/7267), it updates the treesitter config of this extra
=> feat(extras.nushell): update to upstream treesitter

lua/lazyvim/plugins/extras/editor/dial.lua
relevant doc page: https://github.com/monaqa/dial.nvim?tab=readme-ov-file#augend-alias
The specific augend for integers in several languages is a different one than what the comment explaining it suggests.
Changed the augend to the one that includes negative integers like the comment suggests.
=> fix(dial): follow comment explanation for integers

lua/lazyvim/plugins/extras/dap/core.lua
The `dap.continue` is meant to be used also to start the program if no debugging session is active.
The documentation states:
> `continue()` is the main entry-point for users to start debugging an application.
With this change, it should be clearer to the user that `continue` is the way to start a program. Otherwise, one could think to use `Run with args` (which is misleading). At least for me, it was, until I read the dap documentation.
=> docs(dap): document `continue` to be used also for `run`

lua/lazyvim/plugins/coding.lua
Since [this commit in Neovim](https://github.com/neovim/neovim/pull/27339), snippet navigation mappings are set by default to `<tab>` and `<s-tab>`, and hence don't need to be redefined here. Moreover, the core implementation makes sure that those snippet navigation mappings are active only when snippet expansion is happening, and if other user bindings are using those keys, they're restored when snippet navigation ends.
=> fix(snippet): don't set navigation mappings in nightly

lua/lazyvim/plugins/extras/util/project.lua
Unfortunately, the upstream Github repo hasn't been active for over a year. This overwrites the `history.delete_project` function to correctly be able to delete projects. Because of `ipairs` being used, when you delete the first key from the table the `for` loop iteration will just stop, since there will be a gap between the available indices. 
> will iterate over the pairs (`1,t[1]`), (`2,t[2]`), ..., up to the first integer key absent from the table.
There's also a [PR](https://github.com/ahmedkhalf/project.nvim/pull/106/files) for this upstream, but like I mentioned the Github repo hasn't been active for over a year.
Feel free to disregard, since this is obviously something that should be rather fixed upstream under normal circumstances. I just created this PR, since it's such a basic …
=> fix(project.nvim): correctly delete projects

lua/lazyvim/plugins/extras/lang/ruby.lua
Eruby files (.*.erb) are not formatted because the formatter name is incorrect. This PR fixes it.
=> fix(extras): use the correct naming when setting up eruby formatter

lua/lazyvim/plugins/extras/lang/ruby.lua
Solargraph already delegates some diagnostics to Rubocop by itself if it is installed on your system. However, if Rubocop is also enabled as an LSP while you're using Solargraph, then all Rubocop diagnostics are going to be duplicated and shown twice. Once from Solargraph after it calls Rubocop, and again by Rubocop separately running as an LSP.
=> fix(lang/ruby): do not enable Rubocop as LSP if Solargraph is used

lua/lazyvim/plugins/extras/editor/telescope.lua
Currently hitting `<leader>fb` triggers the telescope buffers command but because we're passing the `sort_lastused=true` flag the index starts at the second item. 
This happens because of this line of code in telescope.nvim:
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__internal.lua#L941-L943
This makes it annoying to actually use the tool to find buffers because you have to first type your query then exit insert mode, then scroll one item down, and then hitting enter:
https://github.com/user-attachments/assets/4126d017-df4b-48dc-b6d4-f7d9b8f491ff
When removing that flag it makes the function much more usable in terms of UX since now you can just write your query and hit enter to go straight to it.
=> fix(telescope): buffers to start at final item

lua/lazyvim/plugins/extras/editor/navic.lua
Prior to this, when using the navic Extra, the symbol breadcrumbs shown
in lualine section_c had a background color different from the
background of lualine_c, causing it to standout and not blend in with
some colorschemes.
There were ways around this problem, but hose involved overriding a lot
of highlights. See https://github.com/LazyVim/LazyVim/issues/328
This change uses the new (as of April 2023) lualine component built in
to SmiteshP/nvim-navic, which has a `color_correction` option to fix the
problem described above. This built-in component replaces the manual
method of calling `require("nvim-navic").is_available()` and
`require("nvim-navic").get_location()`.
* https://github.com/SmiteshP/nvim-navic/commit/711e9f117a0936c9d4420a135d658d2ca53a9e99
* …
=> fix(navic): use the same background color as lualine section_c

lua/lazyvim/plugins/extras/lang/scala.lua
Worksheet hovering is a useful feature provided by `metals` to see not just the end result, but also the entire output of a function call, as can be seen here for example:
https://youtu.be/Jv9B1crzpWM?t=16m20s
Having a default key assigned not only makes it more convenient, but also increases discoverability.
(I was also contemplating `<leader>mK` as the mapping to be in line with `K` for regular hover, but I wasn't convinced that the consistency is worth the extra keypress.)
=> feat(scala): add key for worksheet hover

lua/lazyvim/plugins/extras/lang/elixir.lua
Livebook is a subset of Markdown, so we can safely use markdown's treesitter for it.
=> feat(elixir): add support for livebook files (`*.livemd`)

lua/lazyvim/config/options.lua
The ruler option causes numbers to be briefly shown on the dashboard while LazyVim is loading. This MR disables the ruler.
=> fix(options): disable default ruler

lua/lazyvim/plugins/extras/lang/terraform.lua
In the current terraform extra, both `cappyzawa/telescope-terraform.nvim` and
`ANGkeith/telescope-terraform-doc.nvim` are dependencies of `telescope.nvim`.
This should be reversed so that the telescope extensions only load when needed
(I added a `ft` trigger which I think makes the most sense), and not as a
dependency of `telescope.nvim`.
No related issues, just fixed this when the loading time of
`telescope-terraform-doc.nvim` in-particular was annoying (+~30ms startup).
=> fix(extras): lazy-load telescope-terraform plugins

lua/lazyvim/plugins/extras/lang/terraform.lua
Adds a formatter for Packer configuration files (`ft=hcl`), a file type already partially supported by the `lang.terraform` extra.
=> feat(terraform): add formatter for packer files

lua/lazyvim/plugins/extras/ui/alpha.lua
The `dashboard.button` function provided by alpha-nvim expects a string keybind, not a function:
https://github.com/goolord/alpha-nvim/blob/main/lua/alpha/themes/dashboard.lua#L63
Fixes https://github.com/LazyVim/LazyVim/issues/3728.
=> fix(extras): fix alpha-nvim non-string keycodes

lua/lazyvim/config/keymaps.lua, lua/lazyvim/config/options.lua, lua/lazyvim/plugins/coding.lua, lua/lazyvim/plugins/extras/ai/codeium.lua, lua/lazyvim/plugins/extras/ai/copilot.lua, lua/lazyvim/plugins/extras/coding/blink.lua, lua/lazyvim/plugins/extras/coding/luasnip.lua, lua/lazyvim/util/cmp.lua, lua/lazyvim/util/lualine.lua
The whole completion / snippets / AI is very tricky:
- multiple snippet engines
- native snippets on > 0.11 set their own keymaps, but not on 0.10
- multiple completion engines, like `nvim-cmp` and `blink.cmp`
- multiple ai completion engines that have a different API
- user's preference of showing ai suggestions as completion or not
- none of the ai completion engines currently set undo points, which is bad
Solution:
| completion   | snippets     | ai          | ai_cmp | tested? |
|--------------|--------------|-------------|--------|---------|
| nvim-cmp     | native       | copilot     | true   | ✅      |
| nvim-cmp     | native       | copilot     | false  | ✅      |
| nvim-cmp     | native       | codeium     | true   | ✅      |
| nvim-cmp     | native       | codeium     | false  | …
=> feat(ai): better completion/suggestions of AI engines

lua/lazyvim/util/lualine.lua
The color used in lualine was previously static and did not update dynamically when a new colorscheme was applied. This resulted in inconsistencies between the theme and the lualine colors, as the 'local' color table returned the highlight color defined during initialization.
This pull request resolves the issue by ensuring that the lualine colors are always in sync with the current colorscheme. It achieves this by using `LazyVim.ui.fg(HIGHLIGHT)` to dynamically fetch the appropriate highlight colors, making the lualine colors responsive to colorscheme changes.
**Before**
**After**
=> fix(lualine): dynamically fetch the color used in lualine

lua/lazyvim/plugins/lsp/keymaps.lua
Related to 7616816.
Without wrap `lsp_doc_border` does not work
=> fix(lsp): wrap signature_help

lua/lazyvim/plugins/extras/ai/copilot-chat.lua
- Diagnostic help was deprecated and now just proxies to prompt actions (by default diagnostics are auto included in all selections so this feature was no longer necessary)
- Selecton is now visual || buffer by default so the custom selection config is no longer needed too
=> feat(copilot-chat): remove deprecated options

lua/lazyvim/plugins/extras/coding/blink.lua
Auto enable `blink_cmp` integration in catppuccin if the theme plugin is loaded.
**Before**
**After**
=> feat(blink): auto-enable catppuccin integration

lua/lazyvim/plugins/extras/formatting/biome.lua
This PR adds biome as a conform/null-ls formatter.
When using biome lsp formatting directly, the syntax highlighting is flickering. However, it works great when formatting is configured with conform.
To avoid conflicts with Prettier, it is recommended to set
`vim.g.lazyvim_prettier_needs_config = true` In this case, both prettier and biome formatters could be activated simultaneously.
=> feat(extras): add biome formatter

lua/lazyvim/plugins/extras/ai/copilot-chat.lua
nvim-cmp integration was removed in favour of custom autocomplete (it was pointless trying to support all the new completion plugins when its 15 lines to implement something plugin specific)
=> feat(copilot-chat): remove call to nvim-cmp integration

NEWS.md, lua/lazyvim/plugins/extras/ui/alpha.lua, lua/lazyvim/plugins/extras/ui/dashboard-nvim.lua, lua/lazyvim/plugins/extras/ui/mini-starter.lua, lua/lazyvim/plugins/init.lua, lua/lazyvim/plugins/ui.lua
Snacks has a new dashboard plugin that will be LazyVim's default.
Check the docs at https://github.com/folke/snacks.nvim/blob/main/docs/dashboard.md
=> feat(snacks): use `snacks.dashboard` as the default dashboard. moved `dashboard-nvim` to extras

lua/lazyvim/plugins/extras/lang/sql.lua
This PR adds blink.cmp integration with `vim-dadbod-completion` in the SQL extras module. It allows blink.cmp to use the dadbod provider for SQL autocompletion in Neovim.
=> fix(extras): add blink.cmp integration for SQL extra

lua/lazyvim/config/keymaps.lua
If https://github.com/folke/snacks.nvim/pull/89 gets accepted, then we should also update the keymap for Visual mode
None
=> fix(keymaps): `gitbrowse` also in Visual mode

lua/lazyvim/config/keymaps.lua
The Snacks keymaps for `gitbrowse()` and `git.blame_line()` were in a conditional checking if `lazygit` is installed. But both work without `lazygit`.
N/A
N/A
=> fix(snacks): remove lazygit requirement for git browse/blame keymaps

lua/lazyvim/plugins/extras/editor/dial.lua
The python language includes the keywords `and` or `or` for logical operations.
The current `dial.nvim` config does not include an augend for swapping these
keywords.
=> fix(dial): add and/or augend to python ft

lua/lazyvim/plugins/colorscheme.lua
Enable catppuccin's snacks integration by default.
=> feat(colorscheme): enable catppuccin snacks integration by default

lua/lazyvim/plugins/lsp/keymaps.lua
I found an issue where if I'm editing files of different types, say for example `.cs` and `.py` files, they will naturally load the corresponding LSPs for each language. However, if one of those LSPs has keys defined in their `server` config section, then those key maps will leak into the other, so in this case, the `gd` (go to definition) mapping intended for `.cs` buffers is now present in `.py` buffers, causing it not to work. This is currently the case with the `omnisharp` LSP, as it defines a `gd` key map, see: https://github.com/LazyVim/LazyVim/blob/63150fa4c5ec8a6f5c56e9035599a8c8e32dc8ed/lua/lazyvim/plugins/extras/lang/omnisharp.lua#L53-L61
The fix here is to shallow clone the "global" LSP keymaps before adding the LSP server-specific keymaps so the LSP keymaps aren't added to the …
=> fix(lsp): don't leak keymaps from LSP server configs

lua/lazyvim/config/keymaps.lua
Adds a `<leader>gY` keymap that copies the URL from `Snacks.gitbrowse()` to the clipboard. 
This is a feature in other git browse plugins like `vim-rhubarb`, so other people will probably be looking for this when migrating like I did.
Let me know if you'd prefer a different key combination, thanks!
N/A
N/A
=> feat(snacks): add keymap to copy url from gitbrowse

lua/lazyvim/plugins/extras/lang/sql.lua
The blink and sql extras are currently conflicting because the sql extra has a hard dependency on nvim-cmp, which is disabled by the blink extra. Introducing a check for cmp in the sql extra resolves this.
=> fix(sql): only use cmp if it is available

lua/lazyvim/plugins/ui.lua
`indent-blankline.nvim` would act on the snacks dashboard if it was somehow loaded while the dashboard is still open.
Fixes this:
=> fix(ui): disable indent-blankline on `ft=snacks_dashboard`

lua/lazyvim/plugins/extras/lang/sql.lua
`LazyVim.has` was called with the wrong plugin name.
=> fix(sql): fix autocomplete, it was using the wrong plugin name on the `LazyVim.has` check

lua/lazyvim/plugins/extras/ui/mini-indentscope.lua
mini.indentscope would act on the snacks dashboard if it was somehow loaded while the dashboard is still open.
I forgot about mini.indentscope in #4895 :)
**Actually** fixes this:
=> fix(ui): disable mini.indentscope on `ft=snacks_dashboard`

lua/lazyvim/plugins/extras/ai/supermaven.lua
Supermaven completion now works with the latest release of blink.cmp and blink.compat. I'll also take a look at the other ai extras soon.
~A draft for now, until some issues with ghost text are resolved, see https://github.com/Saghen/blink.cmp/issues/257. Alternatively, enabling the supermaven extra could disable ghost text.~
=> fix(supermaven): blink.cmp integration

lua/lazyvim/plugins/extras/ai/codeium.lua, lua/lazyvim/plugins/extras/ai/copilot.lua, lua/lazyvim/plugins/extras/ai/supermaven.lua, lua/lazyvim/plugins/extras/ai/tabnine.lua, lua/lazyvim/plugins/extras/coding/blink.lua
blink.cmp integration for codeium and copilot, and correct menu drawing for codeium, copilot, and supermaven.
I've simplified the blink.cmp config a bit for these extras (especially for copilot, which was extremely nested) by only including the blink.cmp spec if vim.g.ai_cmp is true.
Multiple AI extras can now be enabled at the same time with blink.cmp.
blink.cmp ghost text is now always enabled. Although some ai plugins always display virtual text, at worst it overlaps with blink's ghost text and is not noticable.
Lastly, I can't test copilot because I don't have a subscription, nor do I want to sign up for one, but it should work just as well as the others.
With Codeium:
Multiple extras enabled at the same time:
=> feat(extras.ai): blink.cmp integration and kind overrides for menu drawing

lua/lazyvim/plugins/extras/coding/blink.lua
Update the blink.cmp config for the latest changes.
Mainly fixing the experimental `auto_brackets` support (moved under the `completion` key). The other changes are either the same as the defaults, or commented out - they were simply updated to reflect the new config format.
=> fix(blink): update config for latest changes

lua/lazyvim/plugins/extras/ui/mini-indentscope.lua
Disables mini.indentscope for the buffer on which the `SnacksDashboardOpened` autocmd is called.
closes #4944
=> fix(ui): actually disable mini-indentscope on snacks_dashboard

lua/lazyvim/plugins/extras/lang/tex.lua
Specify the filetype for the keymap  `<localleader>l`  to ensure that this keybinding group only appears when editing TeX files.
=> fix(tex): specify filetype for <localleader>l

lua/lazyvim/plugins/extras/ui/treesitter-context.lua
Load treesitter-context on `LazyFile` instead of `VeryLazy`. IMHO it didn't make sense to load the plugin earlier just so that the toggle is available, especially when the toggle won't actually have any effect anything until a file is opened.
~Previously, treesitter-context was loaded on `VeryLazy` and its toggle map in `opt`, which also `require`d it. Now, mapping happens in config, after treesitter-context is setup (also how toggle is handled in other extras, eg for render-markdown).~
=> fix(extras.treesitter-context): change event back to `LazyFile`

lua/lazyvim/plugins/extras/lang/rust.lua
Fix the lang/rust extra for users that don't use mason. Uses the fix suggested in https://github.com/LazyVim/LazyVim/issues/4957#issuecomment-2521787846, which works perfectly!
Fixes https://github.com/LazyVim/LazyVim/issues/4957
n/a
=> fix(rust): only use mason.nvim if it is present

lua/lazyvim/plugins/extras/vscode.lua
This pull request introduces several new keymaps specifically for VSCode when using LazyVim. These changes aim to enhance the integration between VSCode and LazyVim by adding keymaps for, tab navigation, and syncing nvim undo/redo actions with vscode undo/redo.
- Synced undo/redo lists with VSCode using `VSCodeNotify`: (check https://github.com/vscode-neovim/vscode-neovim/issues/1139 for more details)
- `u` for undo
- `<C-r>` for redo
- Enabled navigation of VSCode tabs similar to LazyVim buffers:
- `<S-h>` to go to the previous editor
- `<S-l>` to go to the next editor
These changes are intended to improve the user experience for those who use LazyVim within VSCode by providing more intuitive and consistent keybindings. Please test these keymaps to ensure they work as expected in your …
=> feat(vscode): add vscode-specific keymaps and sync undo/redo with vscode

lua/lazyvim/plugins/extras/coding/blink.lua
when sorting completion results, blink compares kinds, which can result in an error if the kind is a string
=> fix(blink): set kind to int, not string, if overriding

NEWS.md, lua/lazyvim/config/keymaps.lua, lua/lazyvim/config/options.lua, lua/lazyvim/plugins/coding.lua, lua/lazyvim/plugins/compat/nvim-0_9.lua, lua/lazyvim/plugins/editor.lua, lua/lazyvim/plugins/extras/ai/copilot.lua, lua/lazyvim/plugins/extras/coding/blink.lua, lua/lazyvim/plugins/extras/coding/nvim-cmp.lua, lua/lazyvim/plugins/extras/dap/core.lua, lua/lazyvim/plugins/extras/lang/git.lua, lua/lazyvim/plugins/extras/ui/indent-blankline.lua, lua/lazyvim/plugins/extras/ui/mini-animate.lua, lua/lazyvim/plugins/init.lua, lua/lazyvim/plugins/ui.lua, lua/lazyvim/plugins/util.lua, lua/lazyvim/util/deprecated.lua, lua/lazyvim/util/init.lua, lua/lazyvim/util/lualine.lua, lua/lazyvim/util/mini.lua, lua/lazyvim/util/pick.lua, lua/lazyvim/util/ui.lua
Big new release with a lot of changes and improvements!
Two new plugins have been added, and a lot of plugins have been replaced.
With these changes, default **LazyVim** is now just `34` plugins.
- [fzf-lua](https://github.com/ibhagwan/fzf-lua) as a replacement for [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)
- to use **telescope.nvim** instead, enable the `ui.telescope` extra
- [blink.cmp](https://github.com/saghm/blink.cmp) as a replacement for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
- to use **nvim-cmp** instead, enable the `nvim-cmp` extra
- [dressing.nvim](https://github.com/stevearc/dressing.nvim) (replaced with [fzf-lua](https://github.com/ibhagwan/fzf-lua) and [snacks.input](https://github.com/folke/snacks.nvim))
- …
=> feat(core): new LazyVim release v14.0

lua/lazyvim/plugins/extras/lang/clangd.lua
This prevents the following popup appearing when opening nvim:
```
Failed to run `config` for nvim-cmp
.../lazy/LazyVim/lua/lazyvim/plugins/extras/lang/clangd.lua:108: attempt to index field 'sorting' (a nil value)
- /LazyVim/lua/lazyvim/plugins/extras/lang/clangd.lua:108 _in_ **values**
- ~/.config/nvim/lua/config/lazy.lua:17
- ~/.config/nvim/init.lua:2
```
=> fix(clangd): avoid nil-indexing the completion sorting comparators

lua/lazyvim/plugins/extras/lang/java.lua
This prevents the following error when opening java files when mason is disabled (e.g: NixOS)
```
Failed to run `config` for nvim-jdtls
...im/lazy/LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:149: module 'mason-registry' not found:
no field package.preload['mason-registry']
cache_loader: module mason-registry not found
cache_loader_lib: module mason-registry not found
no file '/nix/store/j3563y13yim4m7qdwk0m8h22648wbifj-luajit-2.1.1713773202-env/share/lua/5.1/mason-registry.lua'
no file '/nix/store/j3563y13yim4m7qdwk0m8h22648wbifj-luajit-2.1.1713773202-env/share/lua/5.1/mason-registry/init.lua'
no file '/nix/store/j3563y13yim4m7qdwk0m8h22648wbifj-luajit-2.1.1713773202-env/lib/lua/5.1/mason-registry.so'
- /LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:149 _in_ **config**
- …
```
=> fix(java): only setup debug adapter config if mason is installed

lua/lazyvim/plugins/extras/coding/blink.lua
Unsets `sources.providers[provider].kind` custom properties to pass blink.cmp config validation.
=> fix(blink): unset provider.kind

lua/lazyvim/plugins/extras/coding/blink.lua
If you would like to enable more sources feel free. I just went with the recommended setting in blink's default configuration. Although on their repo the have it to empty table, but I assumed since you had it to `true` you would at least want the `lsp` source.
=> fix(blink): `draw.treesitter` expects table

lua/lazyvim/plugins/extras/coding/blink.lua
Replace re-defined super-tab `<Tab>` keymap function with the original upstream one, so upstream fixes can propagate.
Related to #5127 
none
none
=> refactor(blink): use upstream <Tab> keymap fn

lua/lazyvim/plugins/extras/editor/fzf.lua
`--no-scrollbar` option is not supported by [fzf-lua](https://github.com/ibhagwan/fzf-lua)
The recommended way is to set `winopts.preview.scrollbar=false`
=> fix(fzf): fzf.lua compatible hidden scrollbar

lua/lazyvim/plugins/extras/ai/codeium.lua
I think the title of the PR says it all. Before the user has to manually load/trigger the plugin via the cmd (`:Codeium Auth`) or by requiring.
PS: The copilot extra also has this event.
~~PPS: Ive also noticed that supermaven doesnt have this event setup, perhaps it suffers to the same issue when this option is disabled?~~
Edit:
For the PPS, have tested supermaven, i can confirm, it loads properly.
=> fix(codeium): doesnt automatically load when `vim.g.ai_cmp` is set to false

lua/lazyvim/plugins/extras/coding/blink.lua
With the version update 5 mins ago, I got an error with this setting.
I'm not sure if removal is the correct way to fix this but it does runs well on my local.
=> fix(blink): remove compatibility with 0.7.6 release

lua/lazyvim/plugins/extras/editor/fzf.lua
Reference: https://github.com/jbyuki/one-small-step-for-vimkind/issues/45#issuecomment-2125749906
Fix nlua debug adapter not responding, which for some reason because of `fzf-lua`.
No screenshot instead I'm providing how to reproduce with assumption `dap.nlua` extra is enabled. Steps:
1. Launch the nlua `:lua require'osv'.launch({port=8086})`
2. Attach from any neovim instance to the debugger
1. Run the debugger
- Can do `<leader>dc`; or
- Can do `:lua require'dap'.continue()`
2. Choose `Attach to running Neovim instance (port = 8086)`
3. Prior to this changes, debugger will got timeout like the following
```text
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `nlua` configuration. Check the logs for errors …
```
=> fix(nlua): debugger not responding

lua/lazyvim/plugins/extras/coding/luasnip.lua
Remove `snippets` from `opts.sources.default` when Luasnip is enabled to not get duplicate snippets.
Fixes #5210
=> fix(luasnip): correctly remove duplicate snippets

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
The mapping `<leader>fR` was showing all recent files instead of the ones in the `cwd` only.
None
=> fix(snacks.picker): fix mapping for `Recent (cwd)`

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
Currently, snacks.picker does not filter symbols based on the kind_filter configured in lazyvim. 
This PR addresses that issue.
nil
=> fix(snacks.picker): respect lazyvim.config.kind_filter

lua/lazyvim/plugins/extras/coding/blink.lua
I've upstreamed the block char vs. icon replacement for Tailwind colors so we shouldn't need this here anymore. I've replaced it by extending the default blink icons instead, just in case they introduce an icon which isn't yet covered by Lazy's, it would still show up (unlikely, but better, no?).
none
none
=> refactor(blink): color swatch icon upstreamed

lua/lazyvim/plugins/extras/util/chezmoi.lua
We have a new picker Snacks picker, it means telescope and fzf-lua can be uninstalled. But chezmoi files still listed only with telescope and fzf-lua. In this pr we add snacks.picker integration if the user has chosen snacks.picker in the LazyVimExtras.
=> feat(chezmoi): add snacks picker integration for chezmoi files

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
`<leader>fp` is the mapping for Telescope and fzf for [Projects](https://www.lazyvim.org/extras/util/project). This PR makes this shortcut consistent for snacks picker.
=> fix(snacks.picker): fix mapping for Projects for consistency

lua/lazyvim/plugins/extras/coding/luasnip.lua
Schedule `jump` in Luasnip `snippet_forward`, so that it doesn't get stuck before the last placeholder.
Fixes #5469
=> fix(luasnip): schedule `jump` to be compatible with blink, nvim-cmp still works after change

lua/lazyvim/config/keymaps.lua
The `<leader>w` mapping, described as "Windows", was causing potentially timeout-related bugs with many other mappings that also started with `<leader>w`.
The problems caused by this are described in detail in issue #5456 and in discussion #4157.
@dpetka2001 Suggested removing it as an experiment, which I tried and found to work.
=> fix(keymaps): remove unneeded and ambiguous `<leader>w` keymap

lua/lazyvim/plugins/extras/editor/snacks_picker.lua
Use `Snacks.picker` for recent files instead of `LazyVim.pick`, because `root_dir` is being propagated to `opts.cwd` and does not correctly filter out recent files when inside nested directories.
None
=> fix(snacks): use `Snacks.picker` for recent files

lua/lazyvim/plugins/extras/editor/refactoring.lua
Fallback to using `require("refactoring").select_refactor()`  if neither of `telescope` or `fzf-lua` is installed. Since `select_refactor()` uses `vim.ui.select` internally, it can use `snacks.picker` if it is enabled.
- [ x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.
=> feat(refactoring): fallback to using vim ui select for refactoring.nvim

lua/lazyvim/plugins/extras/lang/go.lua
Removed a setting from the go lang plugin. The setting now just causes an error:
LSP[gopls] Invalid settings: setting option "analyses": this setting is deprecated, use "the 'fieldalignment' analyzer was removed in gopls/v0.17.0; instead, hover over struct fields to see size/offset information (https://go.dev/issue/66861)" instead
Note: submitted similar request as f96aac6 but was rejected by CI/CD for naming reasons. Changing the name did not help. Retrying.
=> fix(go): update go.lua to eliminate fieldalignment from analyses

lua/lazyvim/plugins/extras/editor/fzf.lua
`fzf-lua` renames their parameter in https://github.com/ibhagwan/fzf-lua/commit/7cede182cf7463376669e102bd10d13f8ce05e52, so this PR updates the parameter also to stop the deprecation warning.
=> feat(editor): update parameter for fzf-lua

lua/lazyvim/config/keymaps.lua
This PR addresses issue #5503 by modifying the behavior of `<leader>xq` and `<leader>xl` so that they toggle the quickfix and location lists rather than simply opening them.
To prevent the full Lua error stack from being printed when no list exists prior to using `copen` or `lopen`, I've wrapped the commands in `pcall` and used `vim.notify` to alert the user in the same manner as before.
#5503
https://github.com/user-attachments/assets/b22b1861-e6e5-4d8a-967e-f760cca15719
=> feat(keymaps): enable toggling in quickfix list and location list

lua/lazyvim/plugins/extras/editor/snacks_picker.lua, lua/lazyvim/plugins/xtras.lua
…shboard-nvim, and mini-starter
Though the snacks.picker extra provides a project picker, it only adds the 'Projects' shortcut to snacks' dashboard, and no to the other three dashboard extra: alpha, dashboard-nvim and mini-starter. In this PR, I added the 'Projects' shortcuts to these three dashboard extras.
- Fixes #5465
alpha
dashboard-nvim
mini.starter
=> feat(snacks.picker): added support for Project shortcuts in other dashboards

lua/lazyvim/plugins/extras/coding/blink.lua
This `blink.cmp` [commit](https://github.com/Saghen/blink.cmp/commit/93215d80346e14763a67d97785dccb1e1c3a6775) introduced a breaking change on main branch. `cmdline` is now top-level and the option is `opts.cmdline.sources = {}`.
I also added a note to remove this hack when the next blink stable release comes out, which should be greater than current 0.11.0 and just do it normally in `opts` instead.
None.
=> fix(blink): `cmdline` is now top-level on main branch

lua/lazyvim/plugins/extras/coding/blink.lua
`blink.cmp` just made a new stable release. So, remove the hack and define the option properly in `opts`.
If I knew it would make a release tonight, I'd definitely hold off my recent PR.
None
=> fix(blink): `blink` released new version, remove previous hack

lua/lazyvim/plugins/extras/coding/blink.lua
Like Saghen already mentioned in the other PR, this [commit](https://github.com/Saghen/blink.cmp/commit/19f60a675eaaf4b160bd6458bfd72fc005da5b3f) does a check based on the `enabled` field before adding sources, so it's no longer needed to define it.
None
=> fix(blink): remove unnecessary `sources` from `cmdline`

lua/lazyvim/plugins/extras/coding/mini-snippets.lua
When using blink.cmp and mini.snippets, the same problem regarding outdated completion items as solved in [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/pull/2126) can arise.
[This](https://github.com/Saghen/blink.cmp/pull/1035) PR has been included into main.
When the PR is included into the next stable release, this PR can be merged.
Current blink release: 0.11.0
=> feat(snippets): mini.snippets standalone and blink.resubscribe

lua/lazyvim/plugins/extras/util/octo.lua
A [PR](https://github.com/pwntester/octo.nvim/pull/858) has landed in `octo.nvim` that adds initial support for `snacks.picker`. Enable it in `octo.nvim` Extra if user uses `snacks.picker`.
I also changed the checks to use `has_extra`. This was needed for `snacks.picker`, since `has("snacks.nvim")` doesn't ensure that user also has `snacks.picker` enabled. For the others I just changed it for conformity, but if you think there might be something wrong about that (that I'm unable to think of), please feel free to change them back.
None
=> feat(octo): add support for snacks picker

lua/lazyvim/plugins/extras/util/chezmoi.lua
This PR enhances the fzf-lua picker for chezmoi by using the built-in `files` picker and by opening the selected file with `ChezmoiEdit` and `vimcmd_entry` to parse the entry. This simplifies the code and adds icons and file preview.
The PR also replaces the config entry in snacks.dashboard with the chezmoi picker, similar to what was already implemented for dashboard-nvim
Current picker:
New picker:
=> feat(chezmoi): enhance fzf-lua chezmoi picker and add snacks.dasbhoard entry

lua/lazyvim/plugins/extras/coding/blink.lua
This blink [commit](https://github.com/Saghen/blink.cmp/commit/010d939e7fd6cb8d8e4a9b1dec228b8405d15fb4) made a change, so that third party sources can provide their own `item.kind_icon` and `item.kind_name`. The problem is that these icons will take precedence over `config.kind_icons[kind]`, which LazyVim sets [here](https://github.com/LazyVim/LazyVim/blob/541b83276e0fe92f7d0d6c9f283cd15ccba5a2fd/lua/lazyvim/plugins/extras/coding/blink.lua#L164-L164).
I noticed that `blink-cmp-copilot` also started providing its own in the items that it returns. I noticed this because I have the following in my configuration `columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind" } }`.  The icon that it uses is a smaller icon one character long, which by default it will scale up and …
=> fix(blink): make sure to use `LazyVim.config.icons.kinds`

lua/lazyvim/plugins/extras/ai/copilot-chat.lua
- Instead of using picker integrations (that are now deprecated), switch to using CopilotChat.select_prompt() that is using `vim.ui.select` which brings the selector integration responsibility to pickers instead of plugin
- Use vim.ui.input instead of vim.fn.input for consistency
Reason why this was deprecated in CopilotChat.nvim (by me) and will be removed in future is because these integrations never made any sense anyway when `vim.ui.select` overrides exist.
Using fzf-lua in my config, outside of LazyNvim but same thing applies:
=> fix(copilot-chat): switch from deprecated picker integrations

lua/lazyvim/plugins/colorscheme.lua
[This commit](https://github.com/catppuccin/nvim/commit/30fa4d122d9b22ad8b2e0ab1b533c8c26c4dde86) renamed a Catppuccin integration; this PR follows the rename.
=> fix(catppuccin): follow renamed integration

lua/lazyvim/plugins/extras/lang/java.lua
Fix:
```
Failed to run `config` for nvim-jdtls
...im/lazy/LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:113: attempt to call field 'root_dir' (a nil value)
- /LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:113 _in_ **full_cmd**
- /LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:169 _in_ **attach_jdtls**
- /LazyVim/lua/lazyvim/plugins/extras/lang/java.lua:286 _in_ **config**
- ~/.local/share/bob/nightly/share/nvim/runtime/filetype.lua:36
- vim/shared.lua:0
- ~/.local/share/bob/nightly/share/nvim/runtime/filetype.lua:35
- vim/_editor.lua:0 _in_ **cmd**
- /persistence.nvim/lua/persistence/init.lua:88 _in_ **load**
- lua:1
- vim/_editor.lua:0 _in_ **action**
- /snacks.nvim/lua/snacks/dashboard.lua:693
```
=> fix(jdtls): root_dir

lua/lazyvim/plugins/extras/lang/haskell.lua
Installing the Haskell extras currently installs telescope.nvim as well,
since the dependency is not marked optional. This marks it optional so
telescope.nvim is no longer pulled in automatically.
=> fix(lang.haskell): prevent Haskell extras from installing telescope.nvim

lua/lazyvim/plugins/editor.lua
https://github.com/MagicDuck/grug-far.nvim is the default find and replace plugin for LazyVim.
It recently added support for being able to do a find / replace within a visual selection to limit the scope of a search.
It did that by introducing a new command called `:GrugFarWithin`. This PR adds that as a `cmd` so it gets loaded by default. Without this PR, you cannot call this command unless you first call `:GrugFar`. This was identified by the author of Grug Far.
There is no issue in this repo, but this feature is related to: https://github.com/MagicDuck/grug-far.nvim/issues/357
I also want to give a shout-out to @MagicDuck who is the author of the plugin. He implemented this feature so fast and has been super helpful in his repo's issue tracker.
=> fix(grug-far): add support for GrugFarWithin so it gets loaded by default

lua/lazyvim/plugins/extras/lang/python.lua
Remove the wrapping `settings` key from `setup()` options.
=> fix(python): remove the wrapping `settings` key from `setup()` options

lua/lazyvim/plugins/extras/lang/clojure.lua
On [this bug](https://github.com/LazyVim/LazyVim/issues/5866) I told about a plugin that was falty on clojure lang extra, with the goal to have him removed but @mitchelkuijpers suggested a new one that I implemented on this PR.
[The plugin](https://github.com/julienvincent/nvim-paredit) is 1:1 with the keymaps of the older one.
https://github.com/LazyVim/LazyVim/issues/5866
=> fix(extras.lang): use 'nvim-paredit' instead 'nvim-treesitter-sexp' as clojure S-exp Plugin

lua/lazyvim/plugins/extras/editor/fzf.lua
add two lines more to the height of prompt window.
- Fixes #6480
=> fix(editor): calculate the height passed to the prompt of fzf-lua properly

lua/lazyvim/plugins/extras/coding/luasnip.lua
This pull request fixes an issue where the `nvim-snippets` plugin was incorrectly marked as disabled due to the missing optional tag in the configuration. By adding the `optional = true` tag, the plugin will no longer appear as disabled when it is not installed.
Before:
After:
=> fix(luasnip): add missing optional tag to garymjr/nvim-snippets

lua/lazyvim/plugins/extras/lang/java.lua
Bug fix jdtls config for compatibility with last lsp refactor.
=> fix(jdtls): allow mason jdtls installation
